/**
 * PROMPTHEUS Werkstatt — deutsche Texte des Namensraums `pluginManager`.
 *
 * Quelle: `packages/client/ui-plugin-manager/src/client/locales.ts`
 * (Fassung 0.2.0-rc.2), **189 Texte**.
 *
 * Der Namensraum deckt die Erweiterungsverwaltung ab: Liste, Einzelheiten,
 * Installation, Installationsquelle, Fortschritt und die Gründe, aus denen
 * etwas nicht geht.
 *
 * **Die Sprache folgt dem Brand (BRAND.md §8):** Deutsch, `ss` statt `ß`,
 * Duz-Form, keine Ausrufezeichen, keine Superlative — und **jede Fehlermeldung
 * nennt einen Weg**. Das ist hier besonders wichtig: fast die Hälfte dieser
 * Texte sind Gründe und Fehler, und ein Grund ohne Handlung wäre eine Sackgasse.
 *
 * **Platzhalter bleiben unverändert** (`{name}`, `{version}`, `{reason}`,
 * `{registries}`, …) — `woerter_pruefen.mjs` prüft das je Schlüssel.
 *
 * **Sicherheitshinweise werden nicht abgeschwächt.** Die Warnung vor
 * unsicheren Quellen und die Frage nach Erlaubnis für Installationsskripte
 * stehen im Harness mit Absicht deutlich; die deutsche Fassung bleibt es auch.
 */

/** Die deutschen Texte des Namensraums `pluginManager`. */
export const erweiterungen: Record<string, string> = {
  // ── Rahmen ─────────────────────────────────────────────────────────────────
  panel: 'Erweiterungen',
  title: 'Erweiterungen',
  intro: 'Erweiterungen einrichten, einschalten und einstellen',
  infoLabel: 'Über Erweiterungen',
  infoDescription: 'Hier stellst du die mitgelieferten Erweiterungen ein und verwaltest weitere. Die Liste der eingebauten Erweiterungen mit ihrem Zustand steht unter „Einstellungen → Eingebaute Erweiterungen".',
  loading: 'Erweiterungen werden gelesen…',
  error: 'Es liessen sich nicht alle Erweiterungen lesen — vermutlich ein Netzproblem.',
  unavailable: 'Diese Einrichtung hat kein verwaltbares Profil. Erweiterungen lassen sich deshalb weder einrichten noch ein- und ausschalten.',
  retry: 'Erneut versuchen',
  refresh: 'Neu laden',
  refreshError: 'Das Neuladen ist gescheitert. Versuche es noch einmal.',
  empty: 'Es ist noch keine Erweiterung eingerichtet.',
  addPlugin: 'Erweiterung hinzufügen',
  restartNotice: 'Änderungen greifen beim nächsten Start',
  overriddenNotice: '{name} wurde gespeichert, aber von einer höherrangigen Einstellung überdeckt und wirkt deshalb zur Zeit nicht',
  bundlesTitle: 'Eingerichtet',
  officialTitle: 'Mitgeliefert',
  statusProblem: 'Auffällig',
  statusBeta: 'Versuchsweise',
  reasonLabel: 'Grund',

  // ── Einzelheiten der Erweiterung ───────────────────────────────────────────
  metadataError: 'Die Angaben zum Paket sind fehlerhaft: {error}',
  versionTag: 'v{version}',
  partsLabel: 'Enthaltene Bestandteile',
  partsEmpty: 'Dieses Paket enthält keine Bestandteile.',
  partsCountTotal: 'zusammen {count}',
  partsCountRunning: '{count} laufen',
  partsCountOff: '{count} abgeschaltet',
  partOff: 'Abgeschaltet',
  partsCountFailed: '{count} auffällig',
  partsFilter: 'Bestandteile filtern',
  partsFilterEmpty: 'Kein Bestandteil passt zum Filter.',
  partToggle: 'Bestandteil {name} einschalten',
  rowPhasePending: 'Wartet auf Voraussetzungen',
  rowPhaseLoading: 'Wird geladen',
  rowPhaseActive: 'Läuft',
  rowPhaseFailed: 'Auffällig',
  rowPhaseUnloading: 'Wird entfernt',
  enableToggle: '{name} einschalten',
  openDetail: '{name} ansehen',
  backToList: 'Zurück zur Liste',
  crumbRoot: 'Erweiterungen',
  backToPackage: 'Zurück zu {name}',
  configureRow: '{name} einstellen',
  rowStateIdle: 'Läuft nicht',
  uninstall: 'Entfernen',
  uninstallLabel: '{name} entfernen',

  // ── Installation ───────────────────────────────────────────────────────────
  installTitle: 'Erweiterung hinzufügen',
  installDescription: 'Gib den Paketnamen, die Adresse des Git-Repositorys oder den Pfad eines örtlichen Ordners ein.',
  installSpecLabel: 'Paketname oder Adresse',
  installSpecPlaceholder: 'zum Beispiel dsh-plugin-whale-pet',
  installGuideToggle: 'Anleitung und Beispiele',
  installGuideHide: 'Anleitung einklappen',
  installGuideIdTitle: 'Den npm-Paketnamen eintragen',
  installGuideIdExample: 'dsh-plugin-whale-pet',
  installGuideIdHint: 'Der Paketname ist der npm-Name (etwa dsh-xxx oder @autor/name). In der README einer Erweiterung steht er hinter dsh plugin add oder pnpm add.',
  installGuideExampleLabel: 'Beispiel:',
  installGitTemplateHint: 'Setze hier die wirkliche Adresse des Git-Repositorys ein',
  installPathTemplateHint: 'Setze hier den wirklichen Pfad des Ordners auf diesem Rechner ein',
  installGuideFill: 'Beispiel einsetzen',
  installGuideFillAria: 'Beispiel {example} einsetzen',
  installGuideSafety: 'Prüfe, ob die Herkunft der Erweiterung vertrauenswürdig ist. Erweiterungen laufen auf diesem Rechner mit deinen Rechten. Eine Erweiterung unbekannter Herkunft kann den DeepSeek Harness beschädigen oder deine Daten lesen und weitergeben.',
  installUpgradeNotice: 'Nach der Installation lässt sich eine Erweiterung noch nicht selbst aktualisieren. Zum Aktualisieren entferne sie und richte die neue Fassung ein.',

  // ── Bezugsquelle ───────────────────────────────────────────────────────────
  registryToggle: 'Bezugsquelle',
  registryLegend: 'Aus welcher npm-Quelle die Erweiterung geladen wird',
  registryDefault: 'Vorgegebene Quelle',
  registryOfficial: 'Die offizielle npm-Quelle',
  registryNpmmirror: 'Spiegel in China',
  registryCustom: 'Eigene Adresse',
  registryCustomPlaceholder: 'https://npm.example.com/',
  registryCustomHint: 'Trage die Adresse einer internen oder eigenen npm-Quelle ein; sie beginnt mit http:// oder https://. Braucht die Quelle eine Anmeldung, lege die Zugangsdaten in ~/.npmrc auf diesem Rechner ab.',
  registryCustomInvalid: 'Die Adresse muss mit http:// oder https:// beginnen',
  registryListSeparator: ', ',
  sentenceSeparator: '',

  // ── Installation: Ablauf ───────────────────────────────────────────────────
  installRun: 'Einrichten',
  installChecking: 'Wird geprüft…',
  installProblemInvalid: 'Dieser Paketname oder diese Adresse ist nicht zu erkennen: {reason}',
  installProblemInstalled: 'Diese Erweiterung ist schon eingerichtet. Zum Aktualisieren entferne sie und richte sie neu ein.',
  installProblemShipped: 'Diese Erweiterung kommt mit DSH. Eine neue Fassung bekommst du mit einem DSH-Update.',
  installProblemNotFound: 'Es wurde keine passende Erweiterung gefunden.',
  installProblemNotPackage: 'Diesen Pfad gibt es nicht, oder dort liegt kein gültiges Erweiterungspaket.',
  installProblemNotBundle: 'Dieses Paket erklärt sich nicht als Bündel und lässt sich deshalb nicht als Erweiterung einrichten: {reason}',
  installProblemNetwork: 'Die Bezugsquelle ist nicht erreichbar. Prüfe die Netzverbindung und versuche es noch einmal.',
  installProblemNetworkAll: 'Keine Bezugsquelle war erreichbar (versucht: {registries}). Prüfe Netz und Proxy oder wähle eine andere Quelle.',
  installProblemUnknown: 'Die Angaben zur Erweiterung liessen sich nicht holen: {reason}',
  installingTitle: 'Die Erweiterung wird eingerichtet…',
  installedTitle: 'Eingerichtet',
  installFailedTitle: 'Das Einrichten ist gescheitert',
  installGithubFailedTitle: 'GitHub ist nicht erreichbar',
  installGithubTimeoutTitle: 'Die Verbindung zu GitHub hat zu lange gedauert',
  installGithubFailedDescription: 'Versuche eine andere Bezugsquelle.',
  installUseGithubMirror: 'Spiegel verwenden',
  installTryAnotherWay: 'Anderen Weg versuchen',
  installPackageLabel: 'Paketname',
  installEdit: 'Bearbeiten',
  installEditAria: 'Zurück zum Bearbeiten',
  installCancelAndEdit: 'Abbrechen und zurück zum Bearbeiten',
  installApplyingCancellationError: 'Der Abbruch wurde nicht bestätigt. Die Einrichtung läuft schon aus. Warte das Ergebnis ab. {reason}',
  installReconcile: 'Zustand abgleichen',
  installUnknownTitle: 'Kein Ergebnis erhalten',
  installUnknownDescription: 'Der Dienst kennt diesen Einrichtungsvorgang nicht mehr. Sieh in der Liste nach und versuche es dann erneut.',
  installResultUnconfirmed: 'Es kam kein Ergebnis zurück. Gleiche den Zustand ab. {reason}',
  installAwaitingAcceptance: 'Der Dienst hat den Auftrag noch nicht angenommen. Sobald die Bestätigung kommt, wird der Abbruch erneut versucht.',
  installBackgroundUnknown: 'Es kam kein Ergebnis zurück. Sieh in der Liste der Erweiterungen nach.',
  installCancel: 'Einrichtung abbrechen',
  installCloseCancels: 'Abbrechen und schliessen',
  installViewTask: 'Einrichtungsauftrag ansehen',
  installUnconfirmedTitle: 'Der Zustand ist noch nicht bestätigt',
  installBackgroundDone: 'Die Erweiterung ist eingerichtet. Das Ergebnis lässt sich ansehen.',
  installBackgroundFailed: 'Das Einrichten ist gescheitert. Einzelheiten lassen sich ansehen.',
  installBackgroundUnconfirmed: 'Der Zustand ist noch nicht bestätigt. Sieh im Einrichtungsauftrag nach.',
  installBackgroundApplying: 'Die Einrichtung läuft schon aus und lässt sich nicht mehr abbrechen. Der Fortschritt lässt sich ansehen.',
  installStarting: 'Die Einrichtung wird vorbereitet…',
  installCancelling: 'Die Einrichtung wird angehalten…',
  installApplying: 'Die Einstellungen werden übernommen. Einen Augenblick…',
  installCancelledShort: 'Abgebrochen',
  installCancelled: 'Die Einrichtung wurde abgebrochen. Die Erweiterung ist nicht eingeschaltet; heruntergeladene Dateien können liegen bleiben.',
  installCancelUnconfirmed: 'Dass die Einrichtung angehalten ist, wurde nicht bestätigt. Versuche den Abbruch erneut oder warte das Ergebnis ab. {reason}',
  installEnableNow: 'Jetzt einschalten',
  installDetailsShow: 'Einzelheiten zeigen',
  installDetailsHide: 'Einzelheiten einklappen',
  installVersion: 'Fassung {version}',
  installSubjectPath: 'Örtlicher Ordner',
  installSubjectGit: 'Git-Repository',
  installSubjectTarball: 'Archivdatei',
  installLocation: 'Eingerichtet unter: {dir}',
  installRetry: 'Erneut versuchen',
  installChangeRegistry: 'Andere Bezugsquelle',
  installAttempt: '{previous} war nicht erreichbar. Es wird mit {registry} versucht ({index}. von {total} Quellen).',
  installAttemptBadge: '{index}. Versuch · {registry}',

  // ── Installationsfehler im Einzelnen ───────────────────────────────────────
  installFailureNetwork: 'Die Netzverbindung ist gescheitert',
  installFailureNetworkAll: 'Keine Bezugsquelle war erreichbar (versucht: {registries}). Prüfe Netz und Proxy oder wähle eine andere Quelle und versuche es erneut.',
  installFailureNetworkHost: '{host} ist nicht erreichbar. Git-Adressen und .tgz-Verweise gehen nicht über die Bezugsquelle; dieser Rechner muss sie selbst erreichen können, sonst ist ein Proxy nötig. Ist die Erweiterung auch bei npm veröffentlicht, trage statt der Adresse den Paketnamen ein.',
  installFailureNotFound: 'Es wurde keine passende Erweiterung gefunden.',
  installFailureNoMatchingVersion: 'Es gibt keine passende Fassung.',
  installFailureDiskFull: 'Der Speicherplatz reicht nicht. Die Einrichtung wurde angehalten.',
  installFailurePermission: 'Es fehlt die Schreibberechtigung. Die Einrichtung geht nicht.',
  installFailureBuildBlocked: 'Ein Installationsskript einer Abhängigkeit braucht deine Erlaubnis, bevor es weitergeht.',
  installFailureBuildBlockedManual: 'pnpm hat ein Installationsskript einer Abhängigkeit angehalten. Erlaube es in der Datei pnpm-workspace.yaml des Profils unter allowBuilds und versuche es dann erneut.',
  installFailureIntegrity: 'Die Prüfsumme der geladenen Datei stimmt nicht.',
  installFailureTimeout: 'Die Einrichtung hat zu lange gedauert.',
  installFailurePnpmMissing: 'pnpm wurde nicht gefunden. Die Einrichtung geht nicht.',
  installFailureGeneric: 'Während der Einrichtung ist ein Fehler aufgetreten. Der Grund steht in den Einzelheiten.',

  // ── Ausgabe des Einrichtungsauftrags ───────────────────────────────────────
  terminalRunning: 'Läuft',
  terminalFailed: 'Gescheitert',
  terminalDone: 'Fertig',
  terminalCopy: 'Kopieren',
  terminalCopied: 'Kopiert',
  terminalNoOutput: 'Keine Ausgabe',
  terminalCollapseAria: 'Ausgabe einklappen',
  terminalCollapse: 'Einklappen',
  terminalExpandAria: 'Die übrigen {n} Zeilen Ausgabe ausklappen',
  terminalExpand: '… {n} weitere Zeilen',
  terminalExitCode: 'Rückgabewert {code}',
  terminalSignal: 'Signal {signal}',
  terminalNoExitCode: 'Nicht ordentlich beendet',

  // ── Abschluss ──────────────────────────────────────────────────────────────
  installDoneNothing: 'Fertig. Es kamen keine neuen Abhängigkeiten dazu.',
  installDoneRestart: 'Eingerichtet. Die Erweiterung wird beim nächsten Start geladen.',
  installDoneApproved: 'Diese Installationsskripte dürfen laufen: {names}',
  installApprovalTitle: 'Installationsskripte brauchen deine Erlaubnis',
  installApprovalDescription: 'Die folgenden Pakete bringen Installationsskripte mit. pnpm führt sie von sich aus nicht aus.',
  installApprovalConsequence: 'Nach deiner Erlaubnis laufen die Skripte auf diesem Rechner mit deinen Rechten. Die Erlaubnis gilt für das aktuelle Profil; danach wird nicht mehr gefragt.',
  installApprovalCaution: 'Erlaube es nur, wenn du diesen Paketen vertraust.',
  installApproveAndRetry: 'Diese Skripte erlauben und erneut versuchen',
  installClose: 'Fertig',
  close: 'Schliessen',
  cancel: 'Abbrechen',

  // ── Entfernen ──────────────────────────────────────────────────────────────
  confirmUninstallTitle: '„{name}" entfernen?',
  confirmUninstallDescription: 'Nach dem Entfernen sind die Funktionen weg, die sie bereitstellt.',
  confirmUninstall: 'Entfernen',

  // ── Fehlschläge ────────────────────────────────────────────────────────────
  failedEnable: 'Das Einschalten ist gescheitert: {reason}',
  failedDisable: 'Das Abschalten ist gescheitert: {reason}',
  failedUninstall: 'Das Entfernen ist gescheitert: {reason}',
  failedRowEnable: 'Der Bestandteil liess sich nicht einschalten: {reason}',
  failedRowDisable: 'Der Bestandteil liess sich nicht abschalten: {reason}',

  // ── Gründe ─────────────────────────────────────────────────────────────────
  reasonManagementRequired: 'Wird zur Verwaltung der Erweiterungen gebraucht und lässt sich deshalb weder abschalten noch entfernen.',
  reasonUnaddressable: 'Die Schicht dieses Profils kann diesen Eintrag nicht eindeutig treffen.',
  reasonUnknownPlugin: 'Diese Erweiterung wurde nicht gefunden.',
  reasonInvalidSpec: 'Gib einen gültigen Paketnamen oder eine Adresse ein.',
  reasonAmbiguousInstall: 'Aus den Änderungen an den Abhängigkeiten lässt sich nicht erkennen, welches Paket eingerichtet wurde.',
  reasonNotBundle: 'Dieses Paket erklärt sich nicht als Bündel und lässt sich deshalb nicht als Erweiterung verwalten.',
  reasonNotRemovable: 'Dieses Paket gehört nicht zum aktuellen Profil, oder es wird zur Verwaltung der Erweiterungen gebraucht.',
  reasonStopProfile: 'In diesem Profil ist HMR nicht eingeschaltet. Ein Paket, das gerade benutzt wird, muss angehalten und dann mit dsh plugin entfernt werden.',
  reasonBundleInUse: 'Andere Einstellungen benutzen noch Bestandteile dieses Bündels. Schalte sie zuerst ab.',
  reasonStaleApproval: 'Die Liste der Skripte, die auf Erlaubnis warten, hat sich geändert. Richte die Erweiterung erneut ein, um sie zu erneuern.',
  reasonIncompatibleVersion: '{plugin} passt nicht zu DSH {runtime} (verlangt {peers}). Der Betrieb kann abstürzen oder Daten verlieren.',
  reasonIncompatibleVersionUnnamed: 'Diese Erweiterung passt nicht zur laufenden DSH-Fassung. Der Betrieb kann abstürzen oder Daten verlieren.',
  reasonIncompatibleInstall: 'Richte eine Fassung ein, die zur laufenden DSH-Fassung passt.',
  reasonIncompatibleInstalled: 'Entferne sie und richte eine Fassung ein, die zur laufenden DSH-Fassung passt.',
  reasonOperationError: 'Die Host-Seite hat einen Fehler gemeldet',
}
