/**
 * Der Namensraum `chat` — die Texte im Gesprächsverlauf.
 *
 * Hier stehen die kurzen Statuszeilen einer Runde, die Verbrauchsangaben,
 * die Verdichtung des Kontexts und die Fehlermeldungen rund um eine Anfrage.
 * Quelle ist die Fassung 0.2.0-rc.2 des Harness; die Schlüssel bleiben
 * unverändert englisch, übersetzt wird nur der Wert.
 *
 * Platzhalter wie `{count}`, `{name}` oder `{duration}` bleiben im deutschen
 * Text erhalten und werden erst zur Anzeigezeit ersetzt. Fachwörter wie JSON,
 * API, Token, TTFT, TPS und Prompt stehen bewusst unübersetzt.
 */

export const gespraechstexte = {
  // ── Schritte einer Runde ──────────────────────────────────────────────────
  'message.stepProcess.thinking': 'Die Anfrage wird ausgewertet',
  'message.stepProcess.read': 'Dateien werden gelesen',
  'message.stepProcess.readImage': 'Bilder werden gelesen',
  'message.stepProcess.write': 'Dateien werden geschrieben',
  'message.stepProcess.search': 'Der Code wird durchsucht',
  'message.stepProcess.edit': 'Dateien werden bearbeitet',
  'message.stepProcess.commands': 'Befehle werden ausgeführt',
  'message.stepProcess.code': 'Code wird ausgeführt',
  'message.stepProcess.webSearch': 'Das Web wird durchsucht',
  'message.stepProcess.webFetch': 'Webseiten werden aufgerufen',
  'message.stepProcess.subagents': 'Unteragenten werden gesteuert',
  'message.stepProcess.plan': 'Der Plan wird aktualisiert',
  'message.stepProcess.questions': 'Warte auf deine Eingabe',
  'message.stepProcess.tools': 'Werkzeuge werden aufgerufen',
  'message.stepProcess.prepare.read': 'Dateien werden zum Lesen vorbereitet',
  'message.stepProcess.prepare.readImage': 'Bilder werden zum Lesen vorbereitet',
  'message.stepProcess.prepare.write': 'Dateien werden zum Schreiben vorbereitet',
  'message.stepProcess.prepare.search': 'Die Codesuche wird vorbereitet',
  'message.stepProcess.prepare.edit': 'Dateien werden zum Bearbeiten vorbereitet',
  'message.stepProcess.prepare.commands': 'Befehle werden vorbereitet',
  'message.stepProcess.prepare.code': 'Die Codeausführung wird vorbereitet',
  'message.stepProcess.prepare.webSearch': 'Die Websuche wird vorbereitet',
  'message.stepProcess.prepare.webFetch': 'Der Seitenaufruf wird vorbereitet',
  'message.stepProcess.prepare.subagents': 'Die Steuerung der Unteragenten wird vorbereitet',
  'message.stepProcess.prepare.plan': 'Die Planaktualisierung wird vorbereitet',
  'message.stepProcess.prepare.questions': 'Fragen werden vorbereitet',
  'message.stepProcess.prepare.tools': 'Werkzeugaufrufe werden vorbereitet',
  'message.stepProcess.done.thinking': 'Anfrage ausgewertet',
  'message.stepProcess.done.read': 'Dateien gelesen',
  'message.stepProcess.done.readImage': 'Bilder gelesen',
  'message.stepProcess.done.write': 'Dateien geschrieben',
  'message.stepProcess.done.search': 'Code durchsucht',
  'message.stepProcess.done.edit': 'Dateien bearbeitet',
  'message.stepProcess.done.commands': 'Befehle ausgeführt',
  'message.stepProcess.done.code': 'Code ausgeführt',
  'message.stepProcess.done.webSearch': 'Web durchsucht',
  'message.stepProcess.done.webFetch': 'Webseiten aufgerufen',
  'message.stepProcess.done.subagents': 'Unteragenten gesteuert',
  'message.stepProcess.done.plan': 'Plan aktualisiert',
  'message.stepProcess.done.questions': 'Fragen gestellt',
  'message.stepProcess.done.tools': 'Werkzeuge aufgerufen',
  'message.stepProcess.joinTwo': '{first} und {second}',
  'message.stepProcess.comma': ', ',
  'message.stepProcess.sharedPrefix': '',
  'message.stepProcess.more': '{title} und weitere',

  // ── Auslöser einer Antwort ────────────────────────────────────────────────
  'message.trigger.request': 'Ausführung angefordert',
  'message.trigger.goal': 'Ziel wird fortgesetzt',
  'message.trigger.agent': 'Aufgabennachricht erhalten',
  'message.trigger.team': 'Teamnachricht erhalten',
  'message.trigger.subagent': 'Status der Unteraufgabe aktualisiert',
  'message.trigger.github': 'GitHub-Ereignis erhalten',
  'message.trigger.webhook': 'Externes Ereignis erhalten',
  'message.trigger.schedule': 'Automatischer Auftrag',
  'message.trigger.job': 'Hintergrundauftrag aktualisiert',
  'message.trigger.plugin': 'Status der Erweiterung aktualisiert',
  'message.trigger.explanation': 'Diese Meldung hat diese Antwort ausgelöst.',

  // ── Lauf einer Runde ──────────────────────────────────────────────────────
  'message.turnProcess.worked': 'Abgeschlossen',
  'message.turnProcess.took': 'Abgeschlossen in ',
  'message.turnProcess.failed': 'Fehlgeschlagen',

  // ── Ansicht, Bilder, Zahlen ───────────────────────────────────────────────
  'view.chat': 'Chat',
  'image.open': 'Ganzes Bild ansehen',
  'image.loading': 'Bild wird geladen…',
  'image.failed': 'Keine Bildvorschau verfügbar. Öffne die Datei ausserhalb der App.',
  'image.dialog': 'Bildvorschau',
  'image.close': 'Bildvorschau schliessen',
  'number.groupSeparator': '.',
  'duration.compactSeconds': '{seconds}s',
  'duration.compactMinutes': '{minutes}m{seconds}s',
  'duration.milliseconds': '{milliseconds}ms',
  'duration.secondUnit': 's',
  'duration.minuteUnit': 'm ',
  'duration.hourUnit': 'h ',

  // ── Statistik des Chats ───────────────────────────────────────────────────
  'stats.counts': '{turns} Runden · {steps} Schritte',
  'stats.cacheHit': 'Cache-Treffer {percent}%',
  'stats.dialog.title': 'Statistik des Chats',
  'stats.dialog.usageTitle': 'Token-Verbrauch',
  'stats.dialog.llmTime': 'Zeit im LLM',
  'stats.dialog.toolTime': 'Zeit in Werkzeugen',
  'stats.dialog.ttft': 'Mittlere Zeit bis zum ersten Token (TTFT)',
  'stats.dialog.speed': 'Token pro Sekunde (TPS)',

  // ── Verlauf und Navigation ────────────────────────────────────────────────
  'chat.loadingHistory': 'Verlauf wird geladen…',
  'chat.loadError': 'Verlauf konnte nicht geladen werden: {message} ({code}). Lade die Seite neu oder prüfe die Verbindung.',
  'chat.loadOlder': 'Ältere laden',
  'chat.toBottom': 'Zurück nach unten',
  'chat.deepDiving': 'Denkt eingehend nach',
  'chat.deepDivingFor': 'Denkt seit {duration} nach ···',
  'chat.turnNavigation.label': 'Rundennavigation',
  'chat.turnNavigation.jump': 'Zu Runde {turn} springen',
  'chat.turnNavigation.jumpLoad': 'Runde {turn} laden und dorthin springen',
  'chat.turnNavigation.turn': 'Runde {turn}',

  // ── Einstellungen zum Verlauf ─────────────────────────────────────────────
  'settings.performance.title': 'Leistung und Verbrauch',
  'settings.performance.description': 'Wähle, wie viele Angaben zu Leistung und Verbrauch angezeigt werden',
  'settings.performance.compact': 'Kompakt',
  'settings.performance.detailed': 'Ausführlich',
  'settings.links.title': 'Chat-Links öffnen in',
  'settings.links.description': 'Wähle, wo Weblinks geöffnet werden',
  'settings.links.sidebar': 'Seitenleiste in der App',
  'settings.links.newTab': 'Standardbrowser',
  'settings.transcript.title': 'Arbeitsdetails',
  'settings.transcript.description': 'Wähle, wie ausführlich Werkzeugaufrufe angezeigt werden',
  'settings.transcript.compact': 'Kompakt',
  'settings.transcript.standard': 'Standard',
  'settings.transcript.detailed': 'Ausführlich',
  'settings.transcript.verbose': 'Alles anzeigen',

  // ── Dateien öffnen ────────────────────────────────────────────────────────
  'fileOpen.title': 'Datei konnte nicht geöffnet werden',
  'fileOpen.unknown': 'Diese Datei konnte nicht geöffnet werden. Prüfe den Pfad oder öffne sie ausserhalb der App.',

  // ── Inhaltsblöcke und Werkzeuge ───────────────────────────────────────────
  'message.extraBlock': 'Zusätzlicher Inhaltsblock',
  'message.systemPrompt': 'System-Prompt',
  'message.systemPromptUpdate': 'System-Prompt aktualisiert',
  'message.toolAdded': 'Werkzeug hinzugefügt: {name}',
  'message.toolRemoved': 'Werkzeug entfernt: {name}',
  'message.toolsAdded': 'Hinzugefügt: {names}',
  'message.toolsAddedCount': '{count} hinzugefügt',
  'message.toolsChanged': '{added} hinzugefügt, {removed} entfernt',
  'message.toolsRemoved': 'Entfernt: {names}',
  'message.toolsRemovedCount': '{count} entfernt',
  'message.toolsUpdated': 'Werkzeuge aktualisiert',

  // ── Kontext und Verdichtung ───────────────────────────────────────────────
  'message.contextInjection': 'Kontexteinfügung',
  'message.contextRecall': 'Rückgriff auf früheren Chat',
  'message.referenceSummary': 'Verwiesener Chat · {labels}',
  'message.referenceSeparator': ', ',
  'message.context.instructions.loaded': 'geladen',
  'message.context.instructions.added': 'hinzugefügt',
  'message.context.instructions.updated': 'aktualisiert',
  'message.context.instructions.removed': 'entfernt',
  'message.context.catalog.replaced': 'Ersetzter Katalog',
  'message.context.catalog.more': '… {count} weitere',
  'message.context.snapshot.supersedes': 'Ersetzt frühere Momentaufnahmen',
  'message.context.relay.from': 'Aus Chat {session}',
  'message.context.recall.counts': '{retained} behalten · {omitted} ausgelassen',
  'message.context.recall.truncated': 'gekürzt',
  'message.compaction': 'Kontext verdichtet',
  'message.compaction.running': 'Kontext wird verdichtet…',
  'message.compaction.completed': '{items} Verlaufseinträge verdichtet (~{tokens} Token)',
  'message.compaction.expand': 'Zusammenfassung der Verdichtung ansehen',
  'message.compaction.unavailable': 'Keine Zusammenfassung der Verdichtung verfügbar',
  'message.compaction.commandTitle': 'compact',
  'message.think': 'Denken',
  'message.unknownSurface': 'Unbekanntes Ereignis der Oberfläche: {type}',
  'message.unknownBlock': 'Unbekannter Inhaltsblock',

  // ── Zählungen in einer Runde ──────────────────────────────────────────────
  'message.turnProcess.toolCalls.one': '{count} Werkzeugaufruf',
  'message.turnProcess.toolCalls.other': '{count} Werkzeugaufrufe',
  'message.turnProcess.messages.one': '{count} Nachricht',
  'message.turnProcess.messages.other': '{count} Nachrichten',
  'message.turnProcess.subagents.one': '{count} Unteragent',
  'message.turnProcess.subagents.other': '{count} Unteragenten',
  'message.turnProcess.thoughtForAWhile': 'Hat eine Weile nachgedacht',
  'message.turnProcess.separator': ' · ',
  'message.stopped': 'Angehalten',
  'message.branch': 'In einen neuen Chat abzweigen',
  'message.branchUnavailable': 'Nur bei der letzten Nachricht einer abgeschlossenen Runde möglich',

  // ── Wiederholung einer Modellanfrage ──────────────────────────────────────
  'message.retry.active': 'Die Modellanfrage wird erneut gesendet',
  'message.retry.cancelled': 'Wiederholung der Modellanfrage abgebrochen',
  'message.retry.started': 'Modellanfrage erneut gesendet',
  'message.retry.scheduled': 'Wartet auf Wiederholung der Modellanfrage',
  'message.retry.status': '{label} ({retry}/{maximum}) · {seconds}s',
  'message.retry.delay': 'Wartezeit bis zur Wiederholung: ',
  'message.retry.failure': 'Grund des Fehlschlags: ',

  // ── Fehler ────────────────────────────────────────────────────────────────
  'message.failure.auth': 'Der API-Schlüssel ist ungültig. Trage in den Einstellungen unter Modelle einen gültigen Schlüssel ein.',
  'message.accountStopped': 'Aufgabe angehalten',
  'message.failure.accountSignedOut': 'Angehalten, weil du dich bei DeepSeek abgemeldet hast. Melde dich wieder an, um fortzusetzen.',
  'message.failure.accountSignInRequired': 'Melde dich bei DeepSeek an und prüfe, ob das Ziel der Anfrage die Kontoanmeldung unterstützt.',
  'message.failure.quota': 'Das Kontingent für Anfragen ist aufgebraucht. Warte auf den nächsten Zeitraum oder erhöhe das Kontingent.',
  'message.turnError': 'Diese Runde ist fehlgeschlagen. Sende die Nachricht erneut oder prüfe die Einstellungen.',
  'message.maxTokens': 'Obergrenze für Ausgabe-Token erreicht',
  'message.maxTokens.hint': 'Die Antwort wurde abgeschnitten; frühere Ausgaben bleiben im Chat erhalten. Sende "continue", damit das Modell fortsetzt.',

  // ── Verbrauch einer Runde ─────────────────────────────────────────────────
  'message.tokensPerSecond': '{tps} tok/s',
  'message.turnUsage.title': 'Verbrauch der Runde',
  'message.turnUsage.consumed': 'Verbrauch {total}',
  'message.turnUsage.model': 'Anbieter / Modell',
  'message.turnUsage.cacheHit': 'Cache-Treffer',
  'message.turnUsage.input': 'Nicht zwischengespeicherte Eingabe',
  'message.turnUsage.cacheRead': 'Zwischengespeicherte Eingabe',
  'message.turnUsage.cacheWrite': 'Schreiben in den Cache',
  'message.turnUsage.output': 'Ausgabe',
  'message.turnUsage.reasoning': ' ({tokens} Denk-Token)',
  'message.turnUsage.count': '{count} tok',

  // ── Befehle und Zeilen ────────────────────────────────────────────────────
  'command.running': 'Läuft…',
  'command.failed': 'Befehl fehlgeschlagen. Prüfe die Ausgabe und starte ihn erneut.',
  'command.done': 'Abgeschlossen',
  'command.title': 'Befehl',
  'row.running': 'Läuft',
  'row.failed': 'Fehlgeschlagen',
  'json.truncated': '… gekürzt, insgesamt {total} Zeichen',

  // ── Datumsformate ─────────────────────────────────────────────────────────
  'clock.md': '{d}.{m}.',
  'clock.ymd': '{d}.{m}.{y}',
}
