/**
 * PROMPTHEUS Werkstatt — deutsche Texte des Namensraums `conversation`.
 *
 * Der größte Namensraum des Harness: **369 Texte**. Quelle ist
 * `packages/client/ui-conversation/src/client/locales.ts` (Fassung 0.2.0-rc.2).
 *
 * **Warum eine eigene Datei je Namensraum.** Bei 369 Einträgen wäre eine einzige
 * Datei unübersichtlich. So bleibt jeder Namensraum für sich lesbar, und ein
 * Harness-Update lässt sich je Namensraum nachziehen.
 *
 * **Die Regeln, die hier gelten** (BRAND.md §8 und die Sprachebene des Harness):
 *   * Deutsch, `ss` statt `ß`, Duz-Form, keine Ausrufezeichen, keine Superlative.
 *   * Jede Fehlermeldung nennt einen Weg.
 *   * Platzhalter (`{count}`, `{size}`, …) bleiben **unverändert** — sie werden
 *     zur Anzeigezeit ersetzt. `woerter_pruefen.mjs` prüft das.
 *   * Deutsche Fassungen eher **kürzer** als länger: viele Texte sitzen in
 *     Knöpfen und Spalten, die für das Englische bemessen sind.
 *
 * **Begriffe, die durchgehalten werden:**
 *   Session → Chat · Turn → Runde · Step → Schritt · Agent → Agent ·
 *   Unteragent → Unteragent · Tool → Werkzeug · Queue → Warteschlange ·
 *   Steer → Einwurf · Approval → Freigabe · Schedule → Zeitplan
 */

/** Die deutschen Texte des Namensraums `conversation`. */
export const gespraech: Record<string, string> = {
  // ── Tastenkürzel und Hinweise ──────────────────────────────────────────────
  'shortcut.newline': 'Zeilenumbruch',
  'shortcut.complementary': 'Gegenstück zu Warteschlange und Einwurf',
  'shortcut.slash': 'Befehlsmenü öffnen',
  'shortcut.mention': 'Verweisemenü öffnen',
  'hint.plan': 'Beschreibe deine Aufgabe, um einen Plan zu erzeugen',
  'hint.goal': 'Gib ein Ziel ein — der Agent arbeitet daran weiter',
  'hint.goal.active': 'Ein Ziel läuft. Du kannst edit, pause, resume oder clear eingeben',
  'placeholder.plan': 'Beschreibe deine Aufgabe, um einen Plan zu erzeugen',
  'placeholder.default': 'Nachricht senden · / für Befehle · @ für Dateien oder Chats',
  'placeholder.unavailable': 'Der Chat ist nicht verfügbar',
  'placeholder.parentOffline': 'Der übergeordnete Chat ist nicht mehr verbunden. Senden geht nicht mehr; anhalten lässt sich der Lauf noch.',
  'placeholder.hero': 'Beschreibe, was du bauen willst · / für Befehle · @ für Dateien oder Chats',
  'placeholder.workspace': 'Wähle einen Arbeitsbereich, um zu beginnen',
  'placeholder.steerQueue': 'Strg+Eingabe wirft alle wartenden Nachrichten ein',

  // ── Eingabezeile ───────────────────────────────────────────────────────────
  'input.commands': 'Datei hinzufügen oder Befehl aufrufen',
  'input.file': 'Datei',
  'input.stop': 'Erzeugung anhalten',
  'input.send': 'Nachricht senden',
  'input.send.queue': 'In die Warteschlange',
  'input.send.steer': 'Als Einwurf senden',

  // ── Anhänge ────────────────────────────────────────────────────────────────
  'attachment.pending': 'Noch nicht gesendete Anhänge',
  'attachment.scrollLeft': 'Anhänge nach links rollen',
  'attachment.scrollRight': 'Anhänge nach rechts rollen',
  'attachment.dropTitle': 'Dateien oder Bilder hierher ziehen, um sie anzuhängen',
  'attachment.dropDesc': 'Höchstens {count} Bilder, jedes bis {size}',
  'attachment.dropBlocked': 'Zur Zeit lassen sich keine Dateien oder Bilder anhängen',
  'attachment.directoryDesktopOnly': 'Ordner gehen nur in der Desktop-Fassung. Im Browser hängst du einzelne Dateien an.',
  'attachment.pathUnavailable': 'Der Ordnerpfad liess sich nicht lesen. Zieh den Ordner noch einmal hinein.',
  'attachment.pathUnsupported': 'Der Pfad enthält Zeichen, auf die sich nicht verweisen lässt. Benenne ihn um und versuche es noch einmal.',

  // ── Bilder ─────────────────────────────────────────────────────────────────
  'image.pending': 'Noch nicht gesendete Bilder',
  'image.openOriginal': 'Original ansehen',
  'image.openOriginalLabel': '{label} — klicken für das Original',
  'image.remove': 'Bild {name} entfernen',
  'image.original': 'Original',
  'image.label': 'Bild',
  'image.loadFailed': 'Das Bild liess sich nicht laden. Klicke, um es erneut zu versuchen.',
  'image.loading': 'Das Bild wird geladen…',
  'image.preview': 'Vorschau des Originals',
  'image.closePreview': 'Vorschau schliessen',
  'image.unsupportedType': 'Nur PNG, JPG, WebP und GIF werden angenommen.',
  'image.tooMany': 'Eine Nachricht nimmt höchstens {count} Bilder.',
  'image.fileTooLarge': 'Ein einzelnes Bild darf höchstens {size} gross sein.',
  'image.totalTooLarge': 'Die Bilder sind zusammen grösser als {size}. Entferne einige.',
  'image.tooManyPixels': 'Das Bild hat zu viele Bildpunkte. Verkleinere es und versuche es noch einmal.',
  'image.dimensionTooLarge': 'Höhe und Breite dürfen {size} px nicht überschreiten. Verkleinere das Bild.',
  'image.modelUnsupported': 'Das gewählte Modell nimmt keine Bilder. Wähle eines, das Bilder versteht.',
  'image.sendFailed': 'Das Bild liess sich nicht senden ({reason}). Füge es noch einmal hinzu.',

  // ── Dateien ────────────────────────────────────────────────────────────────
  'file.pending': 'Noch nicht gesendete Dateien',
  'file.remove': 'Datei {name} entfernen',
  'file.uploading': 'Wird hochgeladen…',
  'file.uploadFailed': 'Der Upload ist gescheitert. Klicke, um es erneut zu versuchen.',
  'file.retry': 'Upload von {name} erneut versuchen',
  'file.stillUploading': 'Die Datei lädt noch. Warte, bis sie fertig ist, und sende dann.',
  'file.sessionUnavailable': 'Der Chat ist nicht verfügbar — Hochladen geht nicht.',
  'file.notStaged': 'Die Datei wurde noch nicht übertragen. Füge sie noch einmal hinzu.',
  'file.label': 'Datei',

  // ── Kontextanzeige ─────────────────────────────────────────────────────────
  'context.aria': 'Kontext zu {percent} belegt',
  'context.used': 'Kontext belegt',
  'context.system': 'Systemanweisung',
  'context.tools': 'Werkzeugbeschreibungen',
  'context.messages': 'Nachrichten',

  // ── Einstellung: Senden bei laufender Arbeit ───────────────────────────────
  'settings.enter.title': 'Senden, während der Agent arbeitet',
  'settings.enter.description': 'Was Eingabe und Senden-Knopf tun, während der Agent läuft. Strg+Eingabe macht immer das andere.',
  'settings.enter.queue': 'In die Warteschlange',
  'settings.enter.steer': 'Als Einwurf',

  // ── Startseite ─────────────────────────────────────────────────────────────
  'hero.headline': 'Talente verdienen…',
  'hero.preview': 'Vorschau',
  'hero.chooseWorkspace': 'Arbeitsbereich wählen',
  'session.hierarchy': 'Chat-Übersicht',

  // ── Aufgabenliste ──────────────────────────────────────────────────────────
  'todo.title': 'Aufgaben',
  'todo.progress.done': '{done} fertig',
  'todo.progress.active': '{active} in Arbeit',
  'todo.progress.pending': '{pending} offen',
  'todo.status.completed': 'Fertig',
  'todo.status.inProgress': 'In Arbeit',
  'todo.status.pending': 'Offen',
  'todo.rowTitle': 'Aufgabenliste ändern',
  'todo.completed': '{done} von {total} fertig',

  // ── Werkzeugtitel ──────────────────────────────────────────────────────────
  'tool.title.createGoal': 'Ziel anlegen',
  'tool.title.getGoal': 'Ziel ansehen',
  'tool.title.updateGoal': 'Ziel ändern',
  'tool.preparing.content': 'Inhalt wird vorbereitet, {kilobytes} KB',
  'tool.title.createSchedule': 'Zeitplan anlegen',
  'tool.title.listSchedules': 'Zeitpläne ansehen',
  'tool.title.deleteSchedule': 'Zeitplan löschen',
  'tool.title.updateSchedule': 'Zeitplan ändern',
  'tool.title.inspectProviders': 'Anbieter prüfen',
  'tool.title.queryRuntime': 'Laufzeit abfragen',
  'tool.title.inspectPlugins': 'Erweiterungen prüfen',
  'tool.title.workflow': 'Arbeitsablauf ausführen',
  'tool.title.ralph': 'Ralph-Schleife ausführen',
  'tool.title.readEvent': 'Ereignis lesen',
  'tool.title.searchEvents': 'Ereignisse durchsuchen',
  'tool.title.traceEvent': 'Ereignis verfolgen',
  'tool.title.searchSessions': 'Chats durchsuchen',
  'tool.title.traceSession': 'Chat verfolgen',
  'tool.title.listModels': 'Verfügbare Modelle ansehen',
  'tool.title.subagent': 'Unteragent starten',
  'tool.title.listAgents': 'Unteragenten ansehen',
  'tool.title.sendMessage': 'Nachricht senden',
  'tool.title.interruptAgent': 'Agent unterbrechen',
  'tool.title.listJobs': 'Hintergrundaufträge ansehen',
  'tool.title.readJob': 'Auftragsausgabe lesen',
  'tool.title.killJob': 'Hintergrundauftrag abbrechen',
  'tool.title.openTerminal': 'Terminal öffnen',
  'tool.title.readTerminal': 'Terminal lesen',
  'tool.title.listTerminals': 'Terminals ansehen',
  'tool.title.signalTerminal': 'Signal an das Terminal senden',
  'tool.title.closeTerminal': 'Terminal schliessen',
  'tool.title.lsp': 'Codesymbole abfragen',
  'tool.title.findDefinition': 'Definition finden',
  'tool.title.findReferences': 'Verwendungen finden',
  'tool.title.findImplementation': 'Umsetzung finden',
  'tool.title.hoverSymbol': 'Symbolinformation ansehen',
  'tool.title.spawnTeammate': 'Mitarbeiter starten',
  'tool.title.createTeamTask': 'Teamaufgabe anlegen',
  'tool.title.getTeamTask': 'Teamaufgabe lesen',
  'tool.title.updateTeamTask': 'Teamaufgabe ändern',
  'tool.title.listTeamTasks': 'Teamaufgaben ansehen',
  'tool.title.waitAgent': 'Auf Unteragenten warten',
  'tool.title.search': 'Suchen',
  'tool.title.read': 'Lesen',
  'tool.title.bash': 'Befehl ausführen',
  'tool.title.write': 'Schreiben',
  'tool.title.edit': 'Bearbeiten',
  'tool.title.code': 'Quelltext',
  'tool.title.generic': 'Werkzeugaufruf',
  'tool.title.inspect': 'Cordis-Umgebung abfragen',
  'tool.title.runCordis': 'Cordis-Erweiterung ausführen',
  'tool.title.stopCordis': 'Cordis-Erweiterung anhalten',
  'tool.title.removeCordis': 'Cordis-Erweiterung entfernen',
  'tool.title.pwsh': 'Befehl ausführen',
  'tool.title.readImage': 'Bild lesen',
  'tool.title.grep': 'Dateiinhalte durchsuchen',
  'tool.title.glob': 'Dateien finden',
  'tool.title.webSearch': 'Im Netz suchen',
  'tool.title.webFetch': 'Seite abrufen',
  'tool.autoReviewRejected': 'Die Auto-Prüfung hat abgelehnt',
  'tool.autoReviewNotExecuted': 'Das Werkzeug wurde nicht ausgeführt. Grund: {reason}',
  'tool.autoReviewReasonFallback': 'Die Auto-Prüfung hat diesen Vorgang nicht erlaubt',

  // ── Einzelheiten: Zustände ─────────────────────────────────────────────────
  'detail.state': 'Zustand',
  'detail.todo.completed': 'Fertig',
  'detail.todo.in_progress': 'In Arbeit',
  'detail.todo.pending': 'Offen',
  'detail.todo.empty': 'Die Aufgabenliste ist leer',
  'todo.diff.initial': 'Erste Aufzeichnung',
  'todo.diff.compare': 'Gegenüber der vorigen Liste',
  'todo.diff.unavailable': 'Die vorige Liste ist nicht verfügbar',
  'todo.diff.noChanges': 'Die Liste hat sich nicht geändert',
  'todo.diff.added': '{count} hinzugefügt',
  'todo.diff.updated': '{count} geändert',
  'todo.diff.removed': '{count} entfernt',
  'todo.diff.unchanged': '{count} unverändert',
  'todo.diff.addedItem': 'Hinzugefügt',
  'todo.diff.updatedItem': 'Zustand geändert',
  'todo.diff.movedItem': 'Reihenfolge geändert',
  'todo.diff.removedItem': 'Entfernt',

  // ── Einzelheiten: Ziel ─────────────────────────────────────────────────────
  'detail.goal.empty': 'Kein Ziel',
  'detail.goal.active': 'Läuft',
  'detail.goal.disarmed': 'Wartet auf Fortsetzung',
  'detail.goal.paused': 'Angehalten',
  'detail.goal.blocked': 'Blockiert',
  'detail.goal.complete': 'Fertig',
  'detail.goal.rounds': 'Runden',
  'detail.goal.reason': 'Grund der Blockade',

  // ── Einzelheiten: Zeitangaben ──────────────────────────────────────────────
  'detail.days': '{count} Tage',
  'detail.hours': '{count} Stunden',
  'detail.minutes': '{count} Minuten',
  'detail.seconds': '{count} Sekunden',

  // ── Einzelheiten: Zeitpläne ────────────────────────────────────────────────
  'detail.schedule.once': 'Einmalig',
  'detail.schedule.every': 'Alle {interval}',
  'detail.schedule.when': 'Geplante Zeit',
  'detail.schedule.frequency': 'Wiederholung',
  'detail.schedule.scheduled': 'Wartet auf Auslösung',
  'detail.schedule.overdue': 'Fällig — wartet darauf, dass der Chat wieder läuft',
  'detail.schedule.empty': 'Kein Zeitplan',
  'detail.schedule.deleted': 'Gelöscht',
  'detail.schedule.count': '{count} Zeitpläne',
  'detail.schedule.daily': 'Täglich {time} ({zone})',
  'detail.schedule.weekly': 'Wöchentlich {days} {time} ({zone})',
  'detail.schedule.cron': 'Cron {expression} ({zone})',
  'detail.weekday.1': 'Montag',
  'detail.weekday.2': 'Dienstag',
  'detail.weekday.3': 'Mittwoch',
  'detail.weekday.4': 'Donnerstag',
  'detail.weekday.5': 'Freitag',
  'detail.weekday.6': 'Samstag',
  'detail.weekday.7': 'Sonntag',
  'detail.weekday.join': ', ',

  // ── Einzelheiten: Ergebnis und Zustände ────────────────────────────────────
  'detail.recordedResult': 'Ergebnis des Aufrufs',
  'detail.empty': 'Noch kein Ergebnis',
  'detail.none': 'Keine',
  'detail.yes': 'Ja',
  'detail.no': 'Nein',
  'detail.moreInInspect': '{count} weitere — unter „Ansehen" nachlesbar',
  'detail.status.running': 'Läuft',
  'detail.status.idle': 'Ruht',
  'detail.status.ready': 'Bereit',
  'detail.status.inactive': 'Läuft nicht',
  'detail.status.provisioning': 'Wird vorbereitet',
  'detail.status.failed': 'Gescheitert',
  'detail.status.completed': 'Fertig',
  'detail.status.deleted': 'Gelöscht',
  'detail.status.killed': 'Abgebrochen',
  'detail.status.accepted': 'Angenommen',
  'detail.status.queued': 'In der Warteschlange',
  'detail.status.exited': 'Beendet',

  // ── Einzelheiten: Felder ───────────────────────────────────────────────────
  'detail.field.id': 'Kennung',
  'detail.field.revision': 'Fassung',
  'detail.field.platform': 'Plattform',
  'detail.field.provider': 'Anbieter',
  'detail.field.model': 'Modell',
  'detail.field.role': 'Rolle',
  'detail.field.context': 'Kontext',
  'detail.field.owner': 'Verantwortlich',
  'detail.field.ready': 'Bereit ab',
  'detail.field.dependencies': 'Voraussetzungen',
  'detail.field.writeScopes': 'Schreibbereich',
  'detail.field.warnings': 'Hinweise',
  'detail.field.diagnostics': 'Fehlerbericht',
  'detail.field.methods': 'Methoden',
  'detail.field.inputSchema': 'Eingabeschema',
  'detail.field.outputSchema': 'Ausgabeschema',
  'detail.field.currentPackage': 'Aktuelle Fassung',
  'detail.field.nextPackage': 'Nächste Fassung',
  'detail.field.latestRun': 'Letzter Lauf',
  'detail.field.packages': 'Fassungen',
  'detail.field.registrations': 'Anmeldungen',
  'detail.field.props': 'Eigenschaften',
  'detail.field.data': 'Daten',
  'detail.field.source': 'Herkunft',
  'detail.field.content': 'Inhalt',
  'detail.field.message': 'Nachricht',
  'detail.field.messageId': 'Nachrichtenkennung',
  'detail.field.root': 'Wurzelknoten',
  'detail.field.pid': 'Prozesskennung',
  'detail.field.type': 'Art',
  'detail.field.time': 'Zeit',
  'detail.field.seq': 'Laufende Nummer',
  'detail.field.turn': 'Runde',
  'detail.field.step': 'Schritt',
  'detail.field.callId': 'Aufrufkennung',
  'detail.field.agents': 'Gestartete Agenten',
  'detail.field.result': 'Ergebnis',
  'detail.field.parent': 'Übergeordnet',
  'detail.field.depth': 'Ebene',
  'detail.field.exitCode': 'Rückgabewert',
  'detail.field.signal': 'Signal',
  'detail.field.previousStatus': 'Zustand vor der Unterbrechung',
  'detail.field.agent': 'Agentenkennung',
  'detail.field.job': 'Auftragskennung',
  'detail.field.task': 'Auftragsinhalt',
  'detail.field.processGroup': 'Prozessgruppe',
  'detail.field.availability': 'Verfügbarkeit',
  'detail.field.bestMatch': 'Passendstes Ereignis',
  'detail.field.target': 'Zielereignis',
  'detail.field.surface': 'Aufgezeichnet',
  'detail.agents.count': '{count} Agenten',
  'detail.jobs.count': '{count} Hintergrundaufträge',
  'detail.terminals.count': '{count} Terminals',
  'detail.tasks.count': '{count} Teamaufgaben',
  'detail.tasks.nextPage': 'Es folgen weitere Aufgaben; die nächste Seite beginnt bei {cursor}',
  'detail.locations.count': '{count} Stellen',
  'detail.location': 'Zeile {line}, Spalte {column}',
  'detail.receipt.delivered': 'Die Nachricht ist angekommen',
  'detail.receipt.interrupt': 'Unterbrechung angefordert',
  'detail.receipt.started': 'Gestartet',
  'detail.receipt.cancel': 'Abbruch angefordert',
  'detail.receipt.alreadyFinished': 'Der Auftrag war schon beendet',
  'detail.receipt.signal': 'Signal gesendet',
  'detail.receipt.closed': 'Geschlossen',
  'detail.receipt.closing': 'Wird geschlossen',
  'detail.wait.noProgress': 'Es läuft kein Unteragent',
  'detail.wait.title': 'Zustand der Unteragenten',
  'detail.wait.timeout': 'Zeit abgelaufen',
  'detail.wait.changed': 'Änderung erkannt',
  'detail.agent.reply': 'Antwort des Agenten',
  'detail.models.title': 'Verfügbare Modelle',
  'detail.output.lines': 'Zeilen {begin}–{end} von {total}',
  'detail.output.truncated': 'Die Ausgabe ist gekürzt',
  'detail.providers.count': '{count} geprüfte Anbieter',
  'detail.plugins.count': '{count} Erweiterungen',
  'detail.workflow.script': 'Ablaufskript',
  'detail.ralph.reportedComplete': 'Der Agent meldet Fertigstellung',
  'detail.ralph.reportedBlocker': 'Der Agent meldet eine Blockade',
  'detail.ralph.limit': 'Die Rundengrenze ist erreicht',
  'detail.report.nextSteps': 'Noch zu tun',
  'detail.trace.replacedBy': 'Ersetzt durch',
  'detail.trace.replacementChain': 'Kette der Ersetzungen',
  'detail.trace.replaces': 'Ersetztes Ereignis',
  'detail.trace.sources': 'Verwiesene Herkünfte',
  'detail.trace.derived': 'Abgeleitetes Ereignis',
  'detail.trace.ancestors': 'Übergeordnete Chats',
  'detail.trace.descendants': 'Abgeleitete Chats',
  'detail.matches.count': '{count} Treffer',
  'detail.matches.capped': 'Die Trefferzahl ist erreicht. Grenze die Suche weiter ein.',
  'detail.event.neighbors': 'Nachbarereignisse',

  // ── Rückfragen ─────────────────────────────────────────────────────────────
  'ask.rowTitle': 'Rückfrage',
  'ask.waiting': 'Wartet auf Antwort',
  'ask.pending': 'Die Arbeit läuft weiter; du kannst noch antworten',
  'ask.pendingDetail': 'Die offene Frage lässt sich im Eingabefeld beantworten',
  'ask.reopen': 'Antworten',
  'ask.review': 'Antwort ansehen',
  'ask.closed': 'Abgeschlossen',
  'ask.closedDetail': 'Diese Frage ist abgeschlossen; das Ergebnis steht im Gespräch darunter.',
  'ask.cancelled': 'Abgebrochen',
  'ask.cancelledDetail': 'Diese Runde wurde abgebrochen, ohne Antwort.',
  'ask.interrupted': 'Unterbrochen',
  'ask.interruptedDetail': 'Diese Runde wurde unterbrochen, ohne Antwort.',
  'ask.answered': '{answered} von {total} beantwortet',
  'ask.skipped': 'Nicht beantwortet',

  // ── Werkzeugzeilen ─────────────────────────────────────────────────────────
  'bash.running': 'Läuft',
  'bash.failed': 'Gescheitert',
  'bash.stopped': 'Angehalten',
  'row.running': 'Läuft',
  'row.preparing': 'Der Aufruf wird vorbereitet',
  'row.failed': 'Gescheitert',
  'row.stopped': 'Angehalten',
  'row.input': 'Eingabe',
  'row.output': 'Ausgabe',
  'row.inspect': 'Ansehen',

  // ── Unterschiede, Lesen, Suchen, Netz ──────────────────────────────────────
  'diff.collapseAria': 'Unterschiede einklappen',
  'diff.expandAria': 'Die übrigen {count} Zeilen Unterschiede ausklappen',
  'diff.expandRest': '… {count} weitere Zeilen',
  'read.window': '{shown} von {total} Zeilen',
  'read.collapseAria': 'Inhalt einklappen',
  'read.expandAria': 'Die übrigen {count} Zeilen ausklappen',
  'read.expandRest': '… {count} weitere Zeilen',
  'search.paths': '{shown} Pfade',
  'search.paths.truncated': '{shown} von {total} Pfaden',
  'search.matches': '{shown} Treffer in {files} Dateien',
  'search.matches.truncated': '{shown} von {total} Treffern in {files} Dateien',
  'search.noResults': 'Kein Ergebnis',
  'search.collapseAria': 'Ergebnisse einklappen',
  'search.expandAria': 'Die übrigen {count} Zeilen Ergebnisse ausklappen',
  'search.expandRest': '… {count} weitere Zeilen',
  'web.noResults': 'Nichts gefunden',
  'web.sourcesTruncated': 'Die Quellenliste ist gekürzt',
  'web.http': 'HTTP',
  'web.contentTruncated': 'Der Inhalt ist gekürzt',
  'details.running': 'Läuft…',

  // ── Warteschlange ──────────────────────────────────────────────────────────
  'queue.count': '{n} wartende Nachrichten',
  'queue.sending': 'Wird gesendet…',
  'queue.image': 'Bild einer wartenden Nachricht',
  'queue.file': 'Wartende Datei {name}',
  'queue.edit': 'Wartende Nachricht bearbeiten',
  'queue.edit.unsupported': 'Sie enthält Nicht-Text; Bearbeiten geht dafür noch nicht.',
  'queue.save': 'Wartende Nachricht speichern',
  'queue.cancelEdit': 'Bearbeiten abbrechen',
  'queue.remove': 'Wartende Nachricht entfernen',
  'queue.steer': 'Als Einwurf senden',
  'queue.steer.unavailable': 'Einwerfen geht nur, während der Agent läuft',
  'queue.editFailed': 'Das Bearbeiten ist gescheitert: Die Nachricht wird vielleicht schon gesendet.',
  'queue.removeFailed': 'Das Entfernen ist gescheitert: Die Nachricht wird vielleicht schon gesendet.',
  'queue.steerFailed': 'Der Einwurf ist gescheitert. Versuche es noch einmal.',
  'error.sessionInUse': 'Dieser Chat wird bereits benutzt, vermutlich von einer anderen laufenden DSH-Fassung (etwa einem weiteren dsh web oder der Desktop-Fassung). Beende die anderen und versuche es noch einmal.',

  // ── Terminal ───────────────────────────────────────────────────────────────
  'terminal.signal': 'Signal {signal}',
  'terminal.exitCode': 'Rückgabewert {code}',
  'terminal.noExitCode': 'Nicht ordentlich beendet',
  'terminal.running': 'Läuft',
  'terminal.failed': 'Gescheitert',
  'terminal.done': 'Fertig',
  'terminal.noOutput': 'Keine Ausgabe',
  'terminal.collapseAria': 'Ausgabe einklappen',
  'terminal.expandAria': 'Die übrigen {n} Zeilen Ausgabe ausklappen',
  'terminal.expandRest': '… {n} weitere Zeilen',
  'terminal.sendInput': '(Eingabe senden)',
  'terminal.session': 'Terminal {sessionId}',

  // ── Befehle ────────────────────────────────────────────────────────────────
  'command.attachmentsUnsupported': '/{command} nimmt keine Anhänge. Entferne sie zuerst.',
}
