/**
 * PROMPTHEUS Werkstatt — deutsche Texte, Runde 3 (Namensräume 11 bis 15).
 *
 * Quellen (Fassung 0.2.0-rc.2):
 *   settings.pluginInventory  ui-settings-plugin-inventory   40
 *   job                       ui-jobs                        39
 *   subagent                  ui-subagent                    39
 *   settings.subagent         ui-settings-subagent           35
 *   sidebar-right             ui-sidebar-right               34
 *
 * **Begriffe, die durchgehalten werden:** Session → Chat · Agent → Agent ·
 * Unteragent → Unteragent · Plugin → Erweiterung · Preset → Voreinstellung ·
 * Job → Hintergrundauftrag · Panel → Bereich.
 *
 * **Platzhalter bleiben unverändert** — `woerter_pruefen.mjs` prüft das je Schlüssel.
 */

/** Einstellungen → Erweiterungsliste (`settings.pluginInventory`). 40 Texte. */
export const erweiterungsliste: Record<string, string> = {
  tab: 'Erweiterungsliste',
  loading: 'Erweiterungen werden gelesen…',
  clientSyncing: 'Die Erweiterungen dieser Seite werden abgeglichen…',
  clientSyncFailed: 'Die Erweiterungen dieser Seite liessen sich nicht abgleichen. Der Zustand auf der Serverseite bleibt, wie er war.',
  clientSyncRetry: 'Abgleich dieser Seite erneut versuchen',
  error: 'Die Erweiterungen lassen sich zur Zeit nicht lesen.',
  metadataError: 'Die Angaben zum Paket sind fehlerhaft: {error}',
  retry: 'Erneut versuchen',
  search: 'Erweiterungen durchsuchen',
  empty: 'Keine Erweiterung vorhanden.',
  emptySearch: 'Keine Erweiterung passt zur Suche.',
  presetTitle: 'Erweiterungen des Chats',
  presetSubtitle: 'Werden je Chat aus der Agenten-Voreinstellung zusammengestellt',
  countUnit: 'Stück',
  switcherLabel: 'Wähle die Agenten-Voreinstellung, die du ansehen willst',
  presetOptionDefault: '{name} (Vorgabe)',
  presetOptionBroken: '{name} (liess sich nicht laden)',
  globalTitle: 'Globale Erweiterungen',
  globalSubtitle: 'Gelten für das System und alle Chats',
  presetProvidedDetail: 'Global abgeschaltet; je Chat kommt sie aus der Agenten-Voreinstellung',
  enabledIn: 'Eingeschaltet in',
  viewInPreset: 'In der Gruppe der Voreinstellung ansehen',
  matchesInOtherPresets: 'In anderen Voreinstellungen passen noch {count} weitere:',
  failedCountLabel: 'gescheitert',
  enabledTag: 'Eingeschaltet',
  disabledTag: 'Abgeschaltet',
  conditionalTag: 'Bedingt eingeschaltet',
  presetEnabledTag: 'In der Voreinstellung eingeschaltet',
  failedTag: 'Start gescheitert',
  moduleLabel: 'Vollständiger Name',
  fromPreset: 'Aus',
  condition: 'Bedingung zum Abschalten',
  configuration: 'Einstellungszustand',
  runtime: 'Laufzustand',
  unobserved: 'Läuft nicht',
  pending: 'Wartet auf Voraussetzungen',
  loadingPhase: 'Wird geladen',
  active: 'Läuft',
  failed: 'Start gescheitert',
  unloading: 'Wird entfernt',
}

/** Hintergrundaufträge (`job`). 39 Texte. */
export const auftraege: Record<string, string> = {
  'count.live.one': '{count} Hintergrundauftrag läuft',
  'count.live.other': '{count} Hintergrundaufträge laufen',
  'count.idle.one': '{count} Hintergrundauftrag',
  'count.idle.other': '{count} Hintergrundaufträge',
  'list.aria': 'Hintergrundaufträge',
  'section.live': 'Laufend',
  'section.settledCount': '{count} abgeschlossen',
  'section.clear': 'Leeren',
  'row.expandAria': 'Die laufende Ausgabe von {label} ausklappen',
  'row.collapseAria': 'Die laufende Ausgabe von {label} einklappen',
  'kill.stop': 'Auftrag {label} anhalten',
  'kill.confirm': 'Zum Bestätigen noch einmal klicken',
  'kill.confirmAction': 'Anhalten bestätigen',
  'kill.failed': 'Das Anhalten ist gescheitert',
  'status.running': 'Läuft',
  'status.stopping': 'Wird angehalten',
  'status.completed': 'Fertig',
  'status.killed': 'Abgebrochen',
  'status.failed': 'Gescheitert',
  'duration.seconds': '{seconds} s',
  'duration.minutes': '{minutes} Min. {seconds} s',
  'duration.hours': '{hours} Std. {minutes} Min.',
  'duration.title.live': 'Läuft seit {duration}',
  'duration.title.done': 'Dauerte {duration}',
  'output.gap': '… frühere Ausgabe wurde verworfen …',
  'output.error': 'Die laufende Ausgabe ist abgerissen: {error}',
  'terminal.signal': 'Signal {signal}',
  'terminal.exitCode': 'Rückgabewert {code}',
  'terminal.noExitCode': 'Nicht ordentlich beendet',
  'terminal.running': 'Läuft',
  'terminal.failed': 'Gescheitert',
  'terminal.done': 'Fertig',
  'terminal.copy': 'Kopieren',
  'terminal.copied': 'Kopiert',
  'terminal.noOutput': '(keine Ausgabe)',
  'terminal.collapse': 'Einklappen',
  'terminal.collapseAria': 'Ausgabe einklappen',
  'terminal.expand': 'Die übrigen {n} Zeilen ausklappen',
  'terminal.expandAria': 'Die eingeklappten {n} Zeilen Ausgabe ausklappen',
}

/** Unteragenten (`subagent`). 39 Texte. */
export const unteragenten: Record<string, string> = {
  'duration.seconds': '{seconds} s',
  'duration.minutes': '{minutes} Min. {seconds} s',
  'duration.hours': '{hours} Std. {minutes} Min. {seconds} s',
  'duration.days': '{days} Tage',
  'duration.daysHours': '{days} Tage {hours} Std.',
  'duration.months': 'etwa {months} Monate',
  'duration.monthsDays': 'etwa {months} Monate {days} Tage',
  'duration.years': 'etwa {years} Jahre',
  'duration.yearsMonths': 'etwa {years} Jahre {months} Monate',
  'duration.exactDays': '{days} Tage {hours} Std. {minutes} Min. {seconds} s',
  'duration.exactTitle': 'Aktive Zeit zusammen: {duration}',
  'tokens.thousand': '{value} Tsd.',
  'tokens.million': '{value} Mio.',
  'tokens.total': '{value} Tok',
  'loading.label': 'Unteragenten werden geladen…',
  'load.error': 'Die Unteragenten liessen sich nicht laden',
  'retry': 'Erneut versuchen',
  'mode.oneShot': 'Einmalig',
  'mode.continuable': 'Fortsetzbar',
  'mode.unknown': 'Art unbekannt',
  'readonly.unknown.body': 'Ob er fortsetzbar ist, zeigt sich erst nach dem Lesen des untergeordneten Chats.',
  'activity.running': 'Läuft',
  'activity.completed': 'Fertig',
  'activity.inactive': 'Läuft zur Zeit nicht',
  'branch.collapse': 'Die untergeordneten Unteragenten von {label} einklappen',
  'branch.expand': 'Die untergeordneten Unteragenten von {label} ausklappen',
  'count.total.one': '{count} Unteragent',
  'count.total.other': '{count} Unteragenten',
  'count.running.one': '{count} Unteragent läuft',
  'count.running.other': '{count} Unteragenten laufen',
  'switcher.aria': 'Unteragent wechseln: {title}',
  'tree.aria': 'Chats der Unteragenten',
  'open.sidebar': 'In der Seitenleiste öffnen',
  'open.sidebar.aria': '{label} in der Seitenleiste öffnen',
  'sidebar.chat': 'Chat',
  'readonly.oneShot.title': 'Aufzeichnung eines einmaligen Unteragenten',
  'readonly.title': 'Dieser Unteragent lässt sich zur Zeit nur lesen',
  'readonly.oneShot.body': 'Ein einmaliger Auftrag nimmt keine weiteren Nachrichten an. Der vollständige Ablauf lässt sich hier nachlesen.',
  'readonly.body': 'Der übergeordnete Chat ist zur Zeit nicht verbunden. Sobald du ihn wieder öffnest, lassen sich Nachrichten senden.',
}

/** Einstellungen → Unteragenten (`settings.subagent`). 35 Texte. */
export const unteragentenEinstellungen: Record<string, string> = {
  overridden: 'Überdeckt',
  reset: 'Auf Vorgabe zurück',
  readOnly: 'Die Einstellungen dieser Einrichtung sind nur lesbar.',
  unavailable: 'Diese Erweiterung ist zur Zeit nicht geladen und lässt sich deshalb nicht einstellen.',
  save: 'Speichern',
  saving: 'Wird gespeichert…',
  saveFailed: 'Diese Einrichtung hat die Werte nicht angenommen. Sie bleiben zum Ändern stehen.',
  subagentTitle: 'Unteragenten',
  subagentDescription: 'Tiefe, Anzahl und Modell der Unteragenten einstellen.',
  subagentLimitsTitle: 'Grenzen',
  subagentMaxDepth: 'Grösste Verschachtelungstiefe',
  subagentDepthHelpLabel: 'Erklärung zur Verschachtelungstiefe',
  subagentDepthHelp: 'Begrenzt, wie tief ein Agent weitere Unteragenten anlegen darf.',
  subagentDepthZero: 'Unteragenten abschalten',
  subagentDepthOne: 'Nur der Hauptagent darf Unteragenten anlegen',
  subagentDepthOverride: 'Hat ein einzelnes Werkzeug eine eigene Tiefe, gilt dessen Einstellung.',
  subagentMaxActive: 'Höchstzahl gleichzeitig laufender Unteragenten',
  subagentCapacityHelpLabel: 'Erklärung zur Höchstzahl',
  subagentCapacityHelp: 'Die Gesamtzahl der Unteragenten, die unter einem Hauptagenten über alle Ebenen gleichzeitig bestehen. Der Hauptagent zählt nicht mit. Ist die Grenze erreicht, werden neue Startanfragen abgelehnt.',
  subagentDepthInvalid: 'Gib eine ganze Zahl ein, die nicht kleiner als 0 ist.',
  subagentCapacityInvalid: 'Gib eine ganze Zahl ein, die nicht kleiner als 1 ist.',
  subagentModelSelectionTitle: 'Modellwahl',
  subagentModelSelectionToggle: 'Dem Agenten erlauben, für Unteragenten ein Modell zu wählen',
  subagentModelSelectionChoose: 'Eingeschaltet darf der Agent aus den unten freigegebenen Modellen für jeden Unteragenten Anbieter, Modell und Denkaufwand wählen. Es wirkt nur auf neue Chats.',
  subagentModelSelectionAllowed: 'Modelle, die der Agent wählen darf',
  subagentModelSelectionLoading: 'Modelle werden geladen…',
  subagentModelSelectionLoadFailed: 'Die Modelle liessen sich nicht laden.',
  subagentModelSelectionRetry: 'Erneut versuchen',
  subagentModelSelectionPartial: 'Einige Anbieter liessen sich zur Zeit nicht laden. Gespeicherte Auswahlen lassen sich trotzdem entfernen.',
  subagentModelSelectionUnavailable: 'Zur Zeit nicht verfügbar',
  subagentModelSelectionUnavailableGroup: 'Gespeichert, aber zur Zeit nicht verfügbar',
  subagentModelSelectionEmpty: 'Zur Zeit meldet kein Anbieter Modelle.',
  subagentModelSelectionRequired: 'Wähle vor dem Speichern mindestens ein Modell.',
  subagentModelSelectionConflict: 'Die Einstellungen wurden anderswo geändert. Verwirf deine Änderung und versuche es erneut.',
  subagentModelSelectionOff: 'Ausgeschaltet benutzt der Unteragent das eingestellte Vorgabemodell oder das des übergeordneten Agenten. Gewählte Modelle bleiben erhalten.',
}

/** Die rechte Spalte (`sidebar-right`). 34 Texte. */
export const rechteSpalte: Record<string, string> = {
  'command.close': 'Die aktuelle Seite oder das Fenster schliessen',
  'command.refresh': 'Die aktuelle Seite neu laden',
  'command.noRefresh': 'Diese Seite lässt sich nicht neu laden',
  'command.toggle': 'Die rechte Spalte aus- oder einklappen',
  'command.fullscreen': 'Bereich vollbilden oder verlassen',
  'command.noSession': 'Wähle zuerst einen Chat',
  'command.noFocus': 'Wähle zuerst den rechten Bereich',
  'command.stale': 'Die Seite hat gewechselt. Wähle den Bereich erneut.',
  'command.collapsed': 'Klappe zuerst die rechte Spalte aus',
  'command.float': 'Ein schwebender Bereich kann das nicht',
  'command.empty': 'Öffne zuerst eine Seite',
  'command.budget': 'Die Grenze von zwei Bereichen ist erreicht',
  'command.width': 'Die Spalte ist zu schmal. Zieh sie breiter und teile dann.',
  'chrome.expand': 'Seitenleiste öffnen',
  'chrome.expandAria': 'Die rechte Seitenleiste öffnen',
  'chrome.collapse': 'Seitenleiste einklappen',
  'chrome.collapseAria': 'Die rechte Seitenleiste einklappen',
  'chrome.toFullscreen': 'Vollbild',
  'chrome.exitFullscreen': 'Vollbild verlassen',
  'dock.emptyPane': 'Leerer Bereich',
  'dock.splitPane': 'Teilen',
  'dock.splitPaneDisabled': 'Die Grenze von zwei Bereichen ist erreicht',
  'dock.splitPaneNarrow': 'Die Spalte ist zu schmal. Zieh sie breiter und teile dann.',
  'dock.closeTab': 'Schliessen',
  'dock.addTab': 'Neue Registerkarte',
  'dock.dockFloat': 'Zurück in die Seitenleiste',
  'dock.closeFloat': 'Schliessen',
  'dock.drop.center': 'Hierher verschieben',
  'dock.drop.left': 'Links teilen',
  'dock.drop.right': 'Rechts teilen',
  'dock.drop.top': 'Oben teilen',
  'dock.drop.bottom': 'Unten teilen',
  'tab.guide.title': 'Beginn',
  'tab.unavailable': 'Für diese Art von Inhalt gibt es noch keine Ansicht.',
}
