/**
 * PROMPTHEUS Werkstatt — deutsche Texte des DeepSeek Harness.
 *
 * Dieses Paket meldet die Namensräume des Harness auf Deutsch an. Der Harness
 * kennt `zh` und `en` (packages/client/locale); `de` ist frei, also belegt
 * dieses Paket es. Ergebnis: eine Stelle für alle deutschen Texte statt 24
 * geänderter Harness-Wörterbücher.
 *
 * **Angepasst an 0.2.0-rc.2** (29.09.2026). Die Fassung 0.2.0 hat die
 * Wörterbücher stark erweitert: aus 117 geprüften Texten der Fassung 0.1.0-rc.8
 * sind in diesen sieben Namensräumen **395** geworden — der Verlauf allein von
 * 14 auf 192. `werkzeuge/woerter_pruefen.mjs` zählt gegen die Harness-Dateien
 * und meldet jeden fehlenden Schlüssel, jeden überzähligen und jeden
 * verlorenen Platzhalter.
 *
 * Die Sprache folgt dem Brand (BRAND.md §8): Deutsch, `ss` statt `ß`,
 * Duz-Form, keine Ausrufezeichen, keine Superlative, und jede Fehlermeldung
 * nennt einen Weg.
 *
 * Nach dem Harness-Grundsatz „Client UI copy is locale-owned" (AGENTS.md der
 * Client-Pakete) gehören alle sichtbaren Texte in ein typisiertes Wörterbuch.
 * Diese Datei ist genau das, nur außerhalb des Repos.
 *
 * Siehe: PROMPTHEUS\vps\Pläne\40_Werkstatt\Deepseek-Dashboard-Maske-Plan.md §6.5
 */

/** Ein deutsches Wörterbuch: Schlüssel des Harness auf deutschen Text. */
export type Woerterbuch = Record<string, string>

/**
 * `sidebar` — die linke Spalte. 5 Schlüssel.
 *
 * Quelle: packages/client/ui-sidebar/src/client/locales.ts
 */
export const sidebar: Woerterbuch = {
  'session.new': 'Neuer Chat',
  'session.new.label': 'Neuen Chat beginnen',
  'toggle.open': 'Seitenleiste öffnen',
  'toggle.collapse': 'Seitenleiste einklappen',
  'panels.label': 'Globale Bereiche',
}

/**
 * `settings.general` — der Rahmen der Einstellungen. 34 Schlüssel.
 *
 * Quelle: packages/client/ui-settings-general/src/client/locales.ts
 * Neu in 0.2.0: die Aktualisierungs-Meldungen der Desktop-Fassung und die
 * Verbindungszustände.
 */
export const settingsGeneral: Woerterbuch = {
  'trigger': 'Einstellungen',
  'shortcut.open': 'Einstellungen öffnen',
  'title': 'Einstellungen',
  'close': 'Schliessen',
  'openDocument': 'Konfigurationsdatei öffnen',
  'openDocument.error': 'Die Konfigurationsdatei liess sich nicht öffnen. Prüfe, ob sie vorhanden ist, und öffne sie dann von Hand.',
  'general.nav': 'Allgemein',
  'general.currentVersion': 'Fassung: {version}',
  'developerTools.title': 'Code-Ansicht zeigen',
  'developerTools.error': 'Das Speichern ist gescheitert. Versuche es noch einmal.',
  'developerTools.description': 'Zeigt den Verlauf, die Code-Änderungen dieser Runde und alle Agenten-Voreinstellungen.',
  'connection.error': 'Die Verbindung ist gestört. Lade die Seite neu.',
  'connection.connecting': 'Verbindung wird wiederhergestellt',
  'connection.connected': 'Verbunden',
  'connection.reconnect': 'Die Verbindung ist gestört. Klicke, um sie sofort wiederherzustellen.',
  'connection.restart': 'Die Verbindung ist abgerissen. Ein Versuch läuft. Klicke, um ihn sofort zu starten.',
  'desktop.update.available': 'Neue Fassung',
  'desktop.update.checking': 'Es wird nach einer neuen Fassung gesucht…',
  'desktop.update.progress': '{percent} %',
  'desktop.update.verifying': 'Die Aktualisierungsdateien werden geprüft…',
  'desktop.update.installing': 'Der Neustart wird vorbereitet…',
  'desktop.update.ready': 'Einspielen und neu starten',
  'desktop.update.retry': 'Aktualisierung erneut versuchen',
  'desktop.update.versionDetail': '{label}: {version}',
  'desktop.update.downloadDetail': 'Aktualisierung wird geladen: {percent} %\nZielfassung: {version}',
  'desktop.update.checkFailed': 'Die Suche nach einer neuen Fassung ist gescheitert. Versuche es später noch einmal.',
  'desktop.update.downloadFailed': 'Die Aktualisierung liess sich nicht laden. Versuche es noch einmal.',
  'desktop.update.installFailed': 'Die Aktualisierung liess sich nicht einspielen. Versuche es später noch einmal.',
  'desktop.update.checkNetworkFailed': 'Die Suche ist gescheitert. Prüfe die Netzverbindung und versuche es noch einmal.',
  'desktop.update.downloadNetworkFailed': 'Das Laden ist gescheitert. Prüfe die Netzverbindung und versuche es noch einmal.',
  'desktop.update.installNetworkFailed': 'Das Einspielen ist gescheitert. Prüfe die Netzverbindung und versuche es noch einmal.',
  'desktop.update.stopFailed': 'Die laufenden Aufgaben liessen sich nicht sicher anhalten. Die Aktualisierung wurde deshalb nicht eingespielt. Versuche es später noch einmal.',
  'desktop.update.tasksChanged': 'Es sind neue Aufgaben angelaufen. Bestätige noch einmal, dass sie angehalten und die Aktualisierung eingespielt werden soll.',
  'desktop.update.tasksUnavailable': 'Der Zustand der Aufgaben liess sich nicht feststellen. Versuche die Aktualisierung noch einmal, wenn der Arbeitsbereich bereit ist.',
}

/**
 * `trajectory` — der Verlauf und seine Werkzeugleiste. 192 Schlüssel.
 *
 * Quelle: packages/client/ui-trajectory/src/client/locales.ts
 * Der größte Namensraum. In 0.1.0-rc.8 waren es 14 Texte, jetzt 192: die
 * Registerkarte ist zur vollständigen Werkzeugansicht geworden.
 */
export const trajectory: Woerterbuch = {
  'view.trajectory': 'Verlauf',
  'toolbar.aria': 'Werkzeugleiste des Verlaufs',
  'toolbar.duration': 'Dauer',
  'toolbar.useActualDuration': 'Wirkliche Dauer verwenden',
  'toolbar.useEqualWidth': 'Alle Schritte gleich breit',
  'toolbar.actualTime': 'Wirkliche Zeit',
  'toolbar.turns': 'Runden',
  'toolbar.expandTurns': 'Alle Runden ausklappen',
  'toolbar.collapseTurns': 'Alle Runden einklappen',
  'toolbar.calls': 'Aufrufe',
  'toolbar.expandCalls': 'Alle Aufrufe ausklappen',
  'toolbar.collapseCalls': 'Alle Aufrufe einklappen',
  'toolbar.search': 'Im Verlauf suchen',
  'toolbar.searchPlaceholder': 'Suchen',
  'kind.system': 'SYSTEM',
  'kind.user': 'NUTZER',
  'kind.context': 'KONTEXT',
  'kind.compacted': 'VERDICHTET',
  'kind.message': 'Nachricht',
  'kind.assistant': 'AGENT',
  'kind.tool': 'WERKZEUG',
  'kind.subtool': 'UNTERWERKZEUG',
  'kind.sub': 'Unter',
  'column.input': 'Eingabe',
  'column.output': 'Ausgabe',
  'column.think': 'Denken',
  'column.time': 'Zeit',
  'column.model': 'Modell',
  'column.tools': 'Werkzeuge',
  'turn.label': 'Runde {turn}',
  'section.betweenTurns': 'Zwischen den Runden',
  'group.message': 'Nachricht',
  'group.step': 'Schritt {step}',
  'group.compaction': 'Verdichtung {seq}',
  'status.failed': 'Gescheitert',
  'status.pending': 'Wartet',
  'status.completed': 'Fertig',
  'timing.notAvailable': 'Nicht verfügbar',
  'timing.notRecorded': 'Nicht aufgezeichnet',
  'timing.stepStartUnavailable': 'Der Schrittbeginn ist nicht verfügbar',
  'timing.firstTokenUnavailable': 'Die Zeit bis zum ersten Token ist nicht verfügbar',
  'timing.usageUnavailable': 'Der Verbrauch ist nicht verfügbar',
  'timing.outputTokensUnavailable': 'Die Zahl der Ausgabe-Token ist nicht verfügbar',
  'timing.durationTooShort': 'Die Dauer ist zu kurz',
  'timing.showLocalTime': 'Ortszeit zeigen',
  'timing.showUnixTimestamp': 'Unix-Zeitstempel zeigen',
  'timing.started': 'Beginn',
  'timing.totalDuration': 'Gesamtdauer',
  'timing.ttft': 'Zeit bis zum ersten Token',
  'timing.generation': 'Erzeugung',
  'timing.throughput': 'Durchsatz',
  'timing.duration': 'Dauer',
  'timing.source': 'Quelle der Zeitmessung',
  'timing.sessionTimestamps': 'Zeitstempel der Sitzung',
  'timing.sessionTimestampsRunning': 'Zeitstempel der Sitzung (läuft)',
  'timing.request': 'Zeitmessung der Anfrage',
  'unit.milliseconds': '{value} ms',
  'unit.seconds': '{value} s',
  'unit.tokens': '{value} Tok',
  'unit.tokensPerSecond': '{value} Tok/s',
  'usage.tokens': 'Token',
  'usage.reasoning': 'Denken',
  'usage.content': 'Inhalt',
  'usage.notReported': 'Kein Verbrauch gemeldet',
  'usage.input': 'Eingabe',
  'usage.cached': 'Aus dem Zwischenspeicher',
  'usage.cacheCreated': 'In den Zwischenspeicher geschrieben',
  'usage.other': 'Sonstiges',
  'usage.output': 'Ausgabe',
  'usage.thisRequest': 'Diese Anfrage',
  'usage.sessionCumulative': 'Zusammengerechnet in dieser Sitzung',
  'options.notRecorded': 'Keine Optionen aufgezeichnet',
  'options.json': 'Optionen der Anfrage als JSON',
  'source.unknown': 'Unbekannt',
  'source.user': 'Nutzereingabe',
  'source.plugin': 'Erweiterung',
  'source.pluginNamed': 'Erweiterung · {plugin}',
  'source.goal': 'Ziel',
  'source.goalRound': 'Ziel · Runde {round}',
  'source.notRecorded': 'Keine Quelle aufgezeichnet',
  'source.messageJson': 'Quelle der Nachricht als JSON',
  'tab.summary': 'Übersicht',
  'tab.rawOutput': 'Rohe Ausgabe',
  'tab.preview': 'Vorschau',
  'tab.raw': 'Rohinhalt',
  'tab.source': 'Quelle',
  'tab.payload': 'Parameter',
  'tab.result': 'Ergebnis',
  'tab.schema': 'Schema',
  'tab.timing': 'Zeitmessung',
  'tab.diff': 'Unterschiede',
  'tab.systemPrompt': 'Systemanweisung',
  'tab.tools': 'Werkzeuge',
  'tab.options': 'Optionen',
  'tab.usage': 'Verbrauch',
  'record.toolCallOnly': '(nur Werkzeugaufruf)',
  'record.noContent': 'Kein Inhalt',
  'record.noPayload': 'Keine Parameter aufgezeichnet',
  'record.noResult': 'Kein Ergebnis aufgezeichnet',
  'record.noOutput': 'Keine Ausgabe',
  'record.schemaUnavailable': 'Das Schema ist nicht verfügbar',
  'record.parameters': 'Parameter',
  'record.resultJson': 'Ergebnis als JSON',
  'record.json': 'JSON',
  'record.parametersJson': 'Parameter als JSON',
  'record.namedParametersJson': '{name}: Parameter als JSON',
  'record.payloadJson': 'Parameter als JSON',
  'record.outputJson': 'Ergebnis als JSON',
  'record.thinking': 'Denken',
  'record.wrapLines': 'Zeilen umbrechen',
  'code.source': 'Quelltext',
  'code.output': 'Ausgabe',
  'code.copySource': 'Quelltext kopieren',
  'code.copyOutput': 'Ausgabe kopieren',
  'code.originalJson': 'Ursprüngliches JSON',
  'code.running': 'Läuft…',
  'record.systemPromptMissing': 'Diese Anfrage trug keine Systemanweisung',
  'record.toolsMissing': 'Diese Anfrage trug keine Werkzeuge',
  'record.systemPrompt': 'Systemanweisung',
  'record.tools': 'Werkzeuge',
  'block.openSummary': 'Übersicht der Werkzeugaufrufe von Block {index} öffnen',
  'block.openSummaryTitle': 'Übersicht der Werkzeugaufrufe öffnen',
  'block.label': 'Block {index} {type}',
  'history.loadingTrajectory': 'Der Verlauf wird geladen…',
  'history.loadingEarlier': 'Der frühere Verlauf wird geladen…',
  'history.loadingEarlierAria': 'Der frühere Verlauf wird geladen…',
  'history.loadEarlier': 'Früheren Verlauf laden',
  'history.clickToLoadEarlier': 'Klicke, um den früheren Verlauf zu laden',
  'request.label': 'Anfrage {request}',
  'request.labelCompaction': 'Anfrage {request} · Verdichtung',
  'request.compaction': 'Verdichtung · {section}',
  'request.compactionPurpose': 'Verdichtung',
  'request.retryProgress': '{retry} von {maximum}',
  'request.collapsedSummary': 'Eingeklappte Übersicht: {kind}, {summary}',
  'request.collapsedTurn': 'Runde',
  'request.collapsedAssistant': 'Agent',
  'request.rowAria': '{request}{kind}, {content}',
  'request.rowPrefix': 'Anfrage {request}, ',
  'request.rowAriaCompaction': 'Anfrage {request}, Verdichtung',
  'request.noContent': 'kein Inhalt',
  'summary.toolCalls.one': '{count} Werkzeugaufruf',
  'summary.toolCalls.other': '{count} Werkzeugaufrufe',
  'summary.steps.one': '{count} Schritt',
  'summary.steps.other': '{count} Schritte',
  'details.event': 'Einzelheiten des Ereignisses',
  'details.resize': 'Breite der Einzelheiten ändern',
  'details.resizeTitle': 'Ziehen ändert die Breite. Ein Doppelklick stellt den Ausgangswert her.',
  'details.close': 'Einzelheiten schliessen',
  'details.status': 'Zustand',
  'details.purpose': 'Zweck',
  'details.provider': 'Anbieter',
  'details.model': 'Modell',
  'details.toolCalls': 'Werkzeugaufrufe',
  'details.subtoolCalls': 'Unterwerkzeug-Aufrufe',
  'details.error': 'Fehler',
  'details.failure.auth': 'Der Zugangsschlüssel ist ungültig. Trage in den Einstellungen unter Modelle einen gültigen ein.',
  'details.retry': 'Erneut versuchen',
  'details.scheduled': 'Eingeplant',
  'details.retryDelay': 'Wartezeit bis zum neuen Versuch',
  'details.result': 'Ergebnis',
  'details.compacted': 'Verdichtet',
  'details.assistantMessage': 'Nachricht des Agenten',
  'details.source': 'Quelle',
  'details.hierarchy': 'Rangfolge',
  'details.toolCall': 'Werkzeugaufruf',
  'timeline.aria': 'Zeitleiste des Verlaufs',
  'timeline.overviewAria': 'Übersicht der Zeitleiste. Waagerecht ziehen, um Ereignisse zu fokussieren.',
  'timeline.noTimingData': 'Keine Zeitdaten',
  'timeline.total': 'Zusammen {duration}',
  'timeline.started': 'Begonnen {time}',
  'timeline.ttftDecoding': 'Erstes Token {ttft} · Entschlüsselung {decoding}',
  'layout.compacting': 'Der Kontext wird verdichtet…',
  'layout.compactionFailed': 'Die Verdichtung des Kontexts ist gescheitert',
  'layout.compacted': 'Der Kontext ist verdichtet',
  'layout.toolCallOnly': 'Nur Werkzeugaufruf',
  'attachment.list': 'Anlagen',
  'attachment.imageName': 'Bild {index}',
  'layout.imageCount': 'Bilder ×{count}',
  'layout.fileAttachments': 'Dateien ×{count}',
  'layout.initialSystemPrompt': 'Erste Systemanweisung',
  'layout.systemPromptUpdated': 'Die Systemanweisung wurde geändert',
  'layout.toolsUpdated': 'Die Werkzeuge wurden geändert',
  'layout.toolAdded': 'Werkzeug hinzugefügt: {name}',
  'layout.toolRemoved': 'Werkzeug entfernt: {name}',
  'layout.toolUpdateNotice': 'Die Werkzeuge wurden geändert',
  'layout.toolsAdded': 'Hinzugefügt: {names}',
  'layout.toolsAddedCount': '{count} hinzugefügt',
  'layout.toolsChanged': '{added} hinzugefügt, {removed} entfernt',
  'layout.toolsRemoved': 'Entfernt: {names}',
  'layout.toolsRemovedCount': '{count} entfernt',
  'layout.systemPromptAndToolsUpdated': 'Systemanweisung und Werkzeuge wurden geändert',
  'layout.compactionInterrupted': 'Die Verdichtung des Kontexts wurde vor dem Ende abgebrochen.',
}

/**
 * `model` — die Modellwahl. 23 Schlüssel.
 *
 * Quelle: packages/client/ui-model-selection/src/client/locales.ts
 * „Select model" heisst hier **„Modell wählen"**.
 */
export const model: Woerterbuch = {
  'provider.account': 'DeepSeek-Konto',
  'command.label': 'Modell',
  'command.description': 'Das Modell für diesen Chat wählen',
  'option.loadError': 'Die Modellliste liess sich nicht laden: {message}',
  'trigger.fallback': 'Modell wählen',
  'trigger.loading': 'Die Modelle werden geladen…',
  'trigger.selectAria': 'Modell wählen',
  'trigger.aria': 'Modell wählen, zur Zeit {model}',
  'trigger.ariaEffort': 'Modell wählen, zur Zeit {model}, Denkaufwand {effort}',
  'menu.aria': 'Modell und Denkaufwand',
  'menu.model': 'Modell',
  'menu.effort': 'Denkaufwand',
  'effort.providerDefault': 'Vorgabe des Anbieters',
  'status.loading': 'Die Modellliste wird erneuert…',
  'error.action': 'Die Modellaktion ist gescheitert: {message}',
  'error.sessionInUse': 'Dieser Chat wird bereits benutzt, vermutlich von einer anderen laufenden DSH-Fassung (etwa einem weiteren dsh web oder der Desktop-Fassung). Beende die anderen und versuche es noch einmal.',
  'action.reload': 'Neu laden',
  'warning.groupLoad': '{name} liess sich nicht laden: {message}',
  'search.placeholder': 'Modelle durchsuchen…',
  'search.clear': 'Suche leeren',
  'search.empty': 'Kein Modell passt zur Suche.',
  'empty.models': 'Es ist kein Modell verfügbar. Prüfe in den Einstellungen unter Modelle, ob ein Anbieter mit Schlüssel eingetragen ist.',
  'empty.efforts': 'Dieses Modell bietet keinen Denkaufwand an.',
}

/**
 * `settings.permission` — die Zugriffsstufe in den Einstellungen. 12 Schlüssel.
 *
 * Quelle: packages/client/ui-permission-presets/src/client/locales.ts
 * Neu in 0.2.0: die drei Stufennamen sind aus dem Quelltext in die Sprachebene
 * gewandert (`preset.readOnly`, `preset.workspaceWrite`, `preset.fullAccess`).
 * Damit braucht es für sie keinen Eingriff in der Profilschicht mehr.
 */
export const settingsPermission: Woerterbuch = {
  'title': 'Zugriffsstufe',
  'description': 'Die Vorgabe-Zugriffsstufe für neue Chats',
  'loading': 'Wird geladen',
  'unavailable': 'Nicht verfügbar',
  'preset.readOnly': 'Nur lesen',
  'preset.workspaceWrite': 'Workspace schreiben',
  'preset.fullAccess': 'Vollzugriff',
  'confirm.title': 'Vollzugriff einschalten?',
  'confirm.description': 'Vollzugriff lässt neue Chats weniger Bestätigungen verlangen und mehr unmittelbar ausführen — auch heikle Vorgänge, Dateiänderungen und Befehle nach draussen. Nutze ihn nur, wenn du den folgenden Aufgaben vertraust.',
  'confirm.acknowledge': 'Ich kenne die Risiken und möchte fortfahren',
  'confirm.cancel': 'Abbrechen',
  'confirm.enable': 'Vollzugriff einschalten',
}

/**
 * `permission.access` — das Zugriffsfenster der laufenden Sitzung. 17 Schlüssel.
 *
 * Quelle: packages/client/ui-permission-presets/src/client/locales.ts (`accessZh`)
 * Der Namensraum heisst `permission.access`, NICHT `settings.permission.access`.
 */
export const settingsPermissionAccess: Woerterbuch = {
  'mode': 'Zugriffsstufe, zur Zeit: {name}',
  'close': 'Schliessen',
  'preset.readOnly': 'Nur lesen',
  'preset.workspaceWrite': 'Workspace schreiben',
  'preset.fullAccess': 'Vollzugriff',
  'confirm.title': 'Vollzugriff einschalten?',
  'confirm.description': 'Vollzugriff verringert die Bestätigungen und lässt den Agenten mehr unmittelbar ausführen — auch heikle Vorgänge, Dateiänderungen und Befehle nach draussen. Nutze ihn nur, wenn du der laufenden Aufgabe vertraust.',
  'confirm.acknowledge': 'Ich kenne die Risiken und möchte fortfahren',
  'confirm.cancel': 'Abbrechen',
  'confirm.enable': 'Vollzugriff einschalten',
  'auto.label': 'Auto-Prüfung',
  'auto.badge': 'VERSUCH',
  'auto.description': 'Läuft ohne Sandkasten. Vor jedem nativen Werkzeugaufruf und jedem inneren PTC-Aufruf prüft dasselbe Modell den Vorgang.',
  'auto.confirm.title': 'Auto-Prüfung einschalten (versuchsweise)?',
  'auto.confirm.description': 'Die Auto-Prüfung läuft ohne Sandkasten. Vor jedem nativen Werkzeugaufruf und jedem inneren PTC-Aufruf entscheidet dasselbe Modell wie der laufende Agent, ob der Vorgang erlaubt ist; was es ablehnt, entscheidest du. Dieses Verfahren ist versuchsweise, kann Vorgänge fälschlich erlauben oder ablehnen und verbraucht zusätzliche Token.',
  'auto.confirm.acknowledge': 'Ich kenne diese Risiken und möchte fortfahren',
  'auto.confirm.enable': 'Auto-Prüfung einschalten',
}

/**
 * `workspace` — Arbeitsbereiche und die Chat-Liste. 112 Schlüssel.
 *
 * Quelle: packages/client/ui-workspace/src/client/locales.ts
 * „Add Workspace" heisst hier **„Workspace hinzufügen"**, wie gewünscht.
 * „Session" wird durchgehend mit **„Chat"** übersetzt — das ist die Sprache,
 * die im Betrieb verstanden wird.
 *
 * Neu in 0.2.0: Archivieren, Anheften und die Filter der Ansicht.
 */
export const workspace: Woerterbuch = {
  'defaultWorkspace.failed': 'Der vorgegebene Arbeitsbereich liess sich nicht anlegen. Wähle über „Workspace wählen" einen Ordner.',
  'group.ungrouped': 'Ohne Zuordnung',
  'session.new': 'Neuer Chat',
  'session.untitled': 'Ohne Namen',
  'shortcut.noSession': 'Wähle zuerst einen Chat',
  'shortcut.noPicker': 'Die Ordnerauswahl ist nicht verfügbar',
  'shortcut.directoryBusy': 'Es wird gerade ein Arbeitsbereich gewählt oder hinzugefügt',
  'shortcut.noCompletedTurn': 'Dieser Chat hat noch keine abgeschlossene Runde',
  'shortcut.forkFailed': 'Der Chat liess sich nicht verzweigen. Versuche es noch einmal.',
  'section.workspaces': 'Arbeitsbereiche',
  'section.sessions': 'Chats',
  'viewOptions.label': 'Ansicht',
  'groupBy.label': 'Gruppieren nach',
  'groupBy.workspace': 'Arbeitsbereich',
  'groupBy.workspaceTree': 'Arbeitsbereich als Baum',
  'groupBy.flat': 'Eine Liste',
  'orderBy.label': 'Sortieren nach',
  'orderBy.manual': 'Eigene Reihenfolge',
  'orderBy.updated': 'Zuletzt geändert',
  'filterBy.label': 'Chats filtern',
  'viewOptions.hideArchived': 'Archivierte ausblenden',
  'viewOptions.showArchived': 'Alle Chats (archivierte zeigen)',
  'viewOptions.onlyArchived': 'Nur archivierte',
  'sessions.expand': 'Die übrigen {n} Chats ausklappen',
  'sessions.collapse': 'Weniger zeigen',
  'empty.none': 'Noch kein Chat',
  'empty.noneArchived': 'Noch kein archivierter Chat',
  'empty.viewOthers': 'Andere Chats ansehen',
  'empty.noMatches': 'Nichts gefunden',
  'workspace.add': 'Workspace hinzufügen',
  'search.sessions.aria': 'Chats durchsuchen',
  'search.placeholder': 'Chatnamen durchsuchen',
  'search.clear': 'Suche leeren',
  'search.results.aria': 'Suchergebnisse',
  'search.pending': 'Der Chatverlauf wird durchsucht…',
  'search.noMatches': 'Kein Chat gefunden',
  'search.hasMore': 'Es werden nur die ersten {n} Treffer gezeigt. Grenze die Suche weiter ein.',
  'menu.addWorkspace': 'Workspace hinzufügen…',
  'picker.loading': 'Arbeitsbereiche werden geladen…',
  'conflict.named': 'Ein Arbeitsbereich mit dem Namen „{name}" gibt es schon.',
  'folderError.title': 'Der Ordner liess sich nicht öffnen',
  'folderError.retry': 'Anderen Ordner wählen',
  'rename': 'Umbenennen',
  'rename.workspace.title': 'Arbeitsbereich umbenennen',
  'rename.session.title': 'Chat umbenennen',
  'field.workspaceName': 'Name des Arbeitsbereichs',
  'field.sessionName': 'Name des Chats',
  'delete.workspace': 'Arbeitsbereich entfernen',
  'delete.desc': '„{name}" wird aus der Liste entfernt. Der Ordner und die Chatverläufe bleiben erhalten; die Chats erscheinen danach unter „Ohne Zuordnung".',
  'delete.pending': 'Der Arbeitsbereich wird entfernt…',
  'menu.fork': 'Chat verzweigen',
  'menu.archiveSession': 'Chat archivieren',
  'menu.unarchiveSession': 'Archivierung aufheben',
  'menu.pinSession': 'Chat anheften',
  'menu.unpinSession': 'Anheftung lösen',
  'row.archived': 'Archiviert',
  'row.pinned': 'Angeheftet',
  'toast.archivedNotOpenable': 'Archivierte Chats lassen sich nicht öffnen. Hebe die Archivierung auf, um ihn zu sehen.',
  'toast.archived': 'Der Chat ist archiviert. Du kannst ',
  'toast.stoppedAndArchived': 'Der Chat wurde angehalten und archiviert. Du kannst ',
  'archive.confirm.title': 'Diesen Chat anhalten und archivieren?',
  'archive.confirm.desc': 'In „{title}" läuft noch Arbeit. Das Archivieren hält sie zuerst an; du kannst den Chat später über den Filter „Alle Chats (archivierte zeigen)" in der Seitenleiste zurückholen. Die angehaltene Arbeit läuft nicht von selbst weiter.',
  'archive.confirm.activity': 'Arbeit, die angehalten wird',
  'archive.confirm.turn': 'Die laufende Runde',
  'archive.confirm.subagents.one': '{n} laufender Unteragent: {names}',
  'archive.confirm.subagents.other': '{n} laufende Unteragenten: {names}',
  'archive.confirm.jobs.one': '{n} Hintergrundauftrag: {names}',
  'archive.confirm.jobs.other': '{n} Hintergrundaufträge: {names}',
  'archive.confirm.schedules.one': '{n} eingeplante Erinnerung: {names}',
  'archive.confirm.schedules.other': '{n} eingeplante Erinnerungen: {names}',
  'archive.confirm.other.one': '{n} weitere Arbeit ({kind})',
  'archive.confirm.other.other': '{n} weitere Arbeiten ({kind})',
  'archive.confirm.listSeparator': ', ',
  'archive.confirm.action': 'Anhalten und archivieren',
  'archive.confirm.pending': 'Wird angehalten und archiviert…',
  'toast.archivedUndo': 'rückgängig machen',
  'toast.archivedOr': ' oder ',
  'toast.archivedFilter': 'archivierte Chats filtern',
  'toast.pinFailed': 'Das Anheften ist gescheitert. Versuche es später noch einmal.',
  'toast.unpinFailed': 'Das Lösen der Anheftung ist gescheitert. Versuche es später noch einmal.',
  'toast.createFailed': 'Der neue Chat liess sich nicht anlegen: {message}',
  'sessions.count.one': '{n} Chat',
  'sessions.count.other': '{n} Chats',
  'actions.workspace.aria': 'Aktionen für den Arbeitsbereich „{name}"',
  'actions.session.aria': 'Aktionen für den Chat „{name}"',
  'actions.archive': 'Archivieren',
  'actions.unarchive': 'Archivierung aufheben',
  'actions.pin': 'Anheften',
  'actions.unpin': 'Anheftung lösen',
  'actions.newSession': 'Neuer Chat',
  'actions.newSession.aria': 'Neuen Chat in „{name}" beginnen',
  'status.running': 'Läuft',
  'status.subagentsRunning.one': '{n} Unteragent läuft',
  'status.subagentsRunning.other': '{n} Unteragenten laufen',
  'status.idle': 'Ruht',
  'status.waitingApproval': 'Wartet auf Freigabe',
  'status.planReview': 'Plan zur Prüfung',
  'status.waitingAnswer': 'Wartet auf Antwort',
  'status.compact.approval': 'Freigabe',
  'status.compact.planReview': 'Planprüfung',
  'status.compact.answer': 'Antwort',
  'status.completed': 'Fertig',
  'hover.created': 'Angelegt {time}',
  'hover.copied': 'Kopiert',
  'date.ymd': '{d}.{m}.{y}',
  'time.now': 'gerade eben',
  'time.minutes': '{n} Min.',
  'time.hours': '{n} Std.',
  'time.days': '{n} T.',
  'time.months': '{n} Mon.',
  'time.years': '{n} J.',
  'time.ago': 'vor {t}',
}
